window.OSP=window.OSP||{};
(function(){
const UI={
 langName:"English",lang:"Language",
 eyebrow:["OSP-1 · Joël Maier","HSLU DMI · Autumn 2026","Ch. 1–3"],
 h1a:"Seven lenses,",h1b:"one question: why",
 lede:"Every theory asks the same organization a different question. You won’t memorize definitions here: you’ll learn [[what each lens sees]], what it misses, and how to spot it in an exam scenario. Tap an underlined name to find out who they were and why they matter.",
 legend:"The yellow rises as you answer that lens’s questions correctly in Detective or Pairs. Tap a lens to open its card.",
 mastered:"mastered",
 tabs:{lesson:"Lesson 1",podcast:"Podcast",cards:"Cards",quiz:"Detective",pairs:"Pairs"},
 found:"Foundations",lensT:"Theoretical lens",idea:"Core idea",ideaHide:"Explain it in your own words first, then check.",
 why:"Why it emerged · why it matters",reason:"How it reasons about a case",sees:"Sees",rec:"Recommends",blind:"Misses",
 seesHide:"What problem would it see?",recHide:"What would it propose?",blindHide:"What is its blind spot?",
 signals:"Signals in an exam scenario",facts:"Fun facts",vx:"IBM workout · prompts to verify with sources",
 recall:"Active recall: hide the answers",tapReveal:"tap to reveal",
 trainOn:"Practise",fAll:"All questions",fNew:"Not yet answered correctly",fWrong:"To review",fOnly:"Only",
 session:"Session",toReview:"To review",deckDone:"Deck finished",nothing:"Nothing to show",
 deckDoneText:"You got {ok} out of {done} right. Wrong answers go to “To review”.",
 nothingText:"No questions match this filter. Try “All questions”.",
 restart:"Start again",caseN:"Case",examLike:"EN · exam style",vxTag:"IBM workout",
 right:"Correct · why",notThis:"Not this one · why",connect:"Connect",nextCase:"Next case →",openCard:"Open card",
 sentence:"Statement",roundEnd:"End of round",whichLens:"Which lens is speaking?",pRight:"Correct",pNo:"No",pNext:"Next →",
 roundDone:"Round complete",roundText:"{ok} out of {done}. The pairs you mix up most are the ones to take into the exam.",reshuffle:"Shuffle and repeat",
 example:"Example",simple:"In plain words",check:"Quick check · answer in your head first",showAns:"Show a possible answer",
 card:"Card",done:"✓ Got it",markDone:"Mark as understood",back:"← Back",fwd:"Next →",step:"Step",slide:"Slides",
 detPick:"Pick a lens and try answering out loud first, then compare.",detProb:"Main problem",detRec:"Recommendation",detBlind:"Blind spot",
 sort:{M:"Market",R:"Redistribution",C:"Reciprocity"},
 pWorld:"Their world · why they asked",pSaid:"What they said",pToday:"Where you see it today",pWork:"Key work",pConfuse:"Don’t confuse with",
 wiki:"Read more on Wikipedia ↗",close:"Close",
 profile:{eyebrow:"Before you start",title:"Create your profile",intro:"Type your name and choose a PIN. With the same name and PIN you get your answers, lesson steps, podcast and notes back on any device.",introLocal:"Type your name and choose a PIN. Your progress is saved in this browser.",name:"Name",pin:"PIN (4–8 digits)",enter:"Enter",recent:"Profiles used on this device",pinNote:"The PIN only keeps two people with the same name apart: don’t use a PIN you use anywhere else.",errName:"Type a name with at least 2 letters.",errPin:"The PIN must have 4 to 8 digits.",errWrong:"This name already exists with a different PIN. Check your PIN, or add your surname’s initial to create a new profile.",errNet:"Can’t reach online saving right now. Try again shortly.",loading:"Loading your profile…",switchP:"Switch profile",remote:"Saved online · {t}",local:"Saved on this device",saving:"Saving…",err:"Online saving failed: I’ll retry on the next change.",devicePin:"This profile’s PIN has changed: please enter again."},
 pod:{
  title:"Podcast · Week 1",
  intro:"The first week’s podcast (about 21 minutes). Listening actively is worth far more than having it on in the background.",
  speed:"Speed",back15:"−15 s",fwd15:"+15 s",resume:"Resume where you left off",
  methodT:"How to listen so it sticks",
  method:["Before you press play, read the three questions below: your brain listens better when it knows what to look for.","Roughly every 5 minutes, pause and note one idea in your own words, plus the course lens it connects to.","When you hear a name (Taylor, Polanyi, Simon…), look up their profile in the Cards: what does the podcast add?","At the end, without replaying, answer the questions. Where you get stuck, go back 15 seconds at a time."],
  qT:"Three questions to keep in mind",
  qs:["Which assumption about people, needs or scarcity comes up, and what does it mean for organizations?","Which Chapter 3 theory does the podcast explain better than the slides? Why?","What could you use right away for the IBM project, keeping FACT separate from ASSUMPTION?"],
  notesT:"Your notes",notesPh:"Minute · idea in your own words · related lens",notesHint:"Notes are saved in this browser only.",
  mark:"Add current minute"
 }
};
const LENSES = [
 {id:"bel",code:"C1",found:true,name:"Beliefs and values",era:"Ch. 1",people:"Needs · Scarcity · Values",
  q:"What do we take for granted about people, needs and value?",
  idea:"Organizations grow out of assumptions. The chain is: assumptions → values → decisions → repeated decisions → structures. Example: “needs are unlimited and resources are scarce” produces competition, optimization, KPIs and the market as the ideal form.",
  why:"It shows that competition, growth and efficiency are not laws of nature but consequences of an assumption. Change the assumption (e.g. “well-being does not require unlimited consumption”) and you get different practices: repair, long product lifecycles, shared ownership.",
  sees:"The hidden premises behind structures and practices.",
  rec:"Make the assumption explicit and ask: what would change if we believed the opposite?",
  blind:"On its own it doesn’t say how to design roles, processes and concrete structures.",
  signals:["“It’s natural for departments to compete”","need → want → demand","growth and efficiency as unquestioned values","alternative assumption: sufficiency, cooperation"],
  facts:["Classic trap: need = perceived deficiency; want backed by purchasing power = a specific desire + the money to afford it; demand = only once you express the intention to buy from a supplier. Wanting something and being able to afford it is not yet demand.","The lecturer’s closing question applies to the whole course: what do we assume about people, needs, scarcity, competition, cooperation, value, success, ownership, growth?"],
  vx:"IBM describes itself as a hybrid cloud and AI company. What assumptions about growth, innovation and people come through in how it presents itself? Growth, technological leadership, constant reinvention?"},
 {id:"pol",code:"C2",found:true,name:"Polanyi and embeddedness",era:"Ch. 2 · 1944",people:"Karl Polanyi (1886–1964)",
  q:"What society is the economy, and the organization, embedded in?",
  idea:"The economy is a social process: society contains the economy, which contains organizations. There are three forms of integration: reciprocity (“I help you, one day someone will help me”), redistribution (a centre collects and distributes) and market exchange (“I pay for what I want”).",
  why:"Polanyi wanted to show that the self-regulating market is a historical construction, not a natural state. For organizations this means they are not closed systems: norms, culture, politics and law shape their decisions.",
  sees:"The social, cultural and institutional context behind economic choices.",
  rec:"To understand an organization, study its environment: laws, culture, relationships, institutions.",
  blind:"Says little about internal structure: roles, processes, decision rights.",
  signals:["favours and help without a price → reciprocity","taxes, central budget, welfare → redistribution","price, contract, salary → market","“the three forms coexist”"],
  facts:["In The Great Transformation (1944) Polanyi calls labour, land and money “fictitious commodities”: they aren’t produced to be sold, yet the market treats them as goods.","Class exercise: a salary is market exchange, but colleagues helping each other unasked is reciprocity, and public university is redistribution. A real company almost always uses several forms at once."],
  vx:"IBM operates in more than 170 countries: how do its practices change across different cultural and legal contexts? Where do you see market (clients), redistribution (internal budgets) and reciprocity (open source, communities)?"},
 {id:"cls",code:"CLS",name:"Classical",era:"~1900–1930",people:"Taylor · Fayol · Weber",
  q:"How do we make work efficient and predictable?",
  idea:"The organization is designed like a machine: clear hierarchy, division of labour, formal roles and rules, standard processes. Management plans and controls, employees execute. The logic: divide → specialize → standardize → control → optimize.",
  why:"Industrialization created huge, fast-growing factories. The problem of the time was coordinating thousands of people at scale, predictably. What remains today: job descriptions, org charts, SOPs and KPIs.",
  sees:"Inefficiency, unclear roles, lack of standardization and control.",
  rec:"Clarify roles, optimize processes, strengthen accountability and standards.",
  blind:"Motivation, informal relationships, adapting to change.",
  signals:["stopwatch, scripts, standard procedures","those who plan ≠ those who execute","more rules and reporting as the response","org chart and chain of command"],
  facts:["At Bethlehem Steel, Taylor studied the loading of pig iron. By his own account, one worker went from about 12.5 to 47 tons a day by following a method prescribed to the second.","Fayol was a mining engineer who became a company director. He described the functions of management: planning, organizing, commanding, coordinating, controlling.","Weber saw bureaucracy as rational, but warned it could become a shell “hard as steel”, which became the famous English phrase iron cage."],
  vx:"In the 1960s IBM was the symbol of the large, hierarchical, standardized corporation. What remains of that logic today (global processes, KPIs, compliance)? And where does it slow things down?"},
 {id:"hr",code:"HR",name:"Human Relations",era:"~1930–1960",people:"Mayo · Maslow · Herzberg · McGregor",
  q:"What role do people, motivation and relationships play?",
  idea:"People are not parts of a production system. They are motivated by more than money: recognition, belonging, meaningful work. Informal groups influence performance, leadership style matters, and management’s assumptions about people shape the organization.",
  why:"The classical lens couldn’t explain certain results: at Hawthorne, productivity changed for social reasons, not technical ones. What remains today: engagement, team development, psychological safety and employee experience.",
  sees:"Low motivation, weak relationships, poor employee experience.",
  rec:"Participation, leadership development, recognition, communication, teamwork.",
  blind:"Structural inefficiencies and the external environment.",
  signals:["attention, recognition, belonging","“pay isn’t enough”","the informal group sets the pace","the manager thinks employees are lazy"],
  facts:["Hawthorne Works, Western Electric, near Chicago, 1920s: productivity rose whether the lighting was increased or reduced. The term “Hawthorne effect” only appeared in 1958, coined by Henry Landsberger.","The famous pyramid wasn’t drawn by Maslow: the pyramid shape was popularized by other authors after him.","Herzberg: salary is a hygiene factor. If it’s too low it creates dissatisfaction, but raising it doesn’t create real motivation; that comes from responsibility, recognition and growth.","McGregor (1960): Theory X and Theory Y aren’t two types of workers, but two sets of managers’ assumptions, which tend to become self-fulfilling."],
  vx:"The THINK motto goes back to Thomas J. Watson Sr. How does IBM’s culture translate today for tens of thousands of remote or hybrid employees? A great area for the Q&A."},
 {id:"dec",code:"DEC",name:"Decision-making",era:"~1940–1960",people:"Herbert Simon · James March",
  q:"How are decisions really made, with limited information?",
  idea:"Bounded rationality: nobody has complete information, unlimited time and infinite cognitive capacity. So people simplify, consider only a few alternatives and choose the first acceptable solution (satisficing). Organizations create rules, routines and structures to support decisions.",
  why:"Earlier theories assumed a manager able to find the optimal solution. Simon showed this is an illusion. The design consequence: designing an organization is also designing decisions, i.e. who gets which information and who may decide what.",
  sees:"Poorly distributed information and authority, too many approvals, bottlenecks.",
  rec:"Clarify decision rights, improve information flow, remove bottlenecks.",
  blind:"Culture, the external environment, emotional factors.",
  signals:["incomplete or misplaced information","“the first acceptable option”","too many approval layers","routines so not every case is analysed"],
  facts:["Herbert Simon won the Nobel Prize in Economics (1978) and the Turing Award (1975): he was one of the pioneers of artificial intelligence.","Satisficing is a word Simon coined, blending satisfy and suffice.","March, with Cohen and Olsen, proposed the garbage can model (1972): in organizations, problems, solutions and decision-makers sometimes meet almost by chance."],
  vx:"In a global matrix organization, who decides what between countries, business lines and functions? Where do bottlenecks arise? A perfect question for the Q&A."},
 {id:"sys",code:"SYS",name:"Systems and sociotechnical",era:"~1950–1970",people:"Bertalanffy · Katz & Kahn · Trist & Emery",
  q:"How does the organization interact with its environment?",
  idea:"Everything is connected: change one part and you affect many others. The organization is an open system that takes resources from its environment, transforms them and returns them. From the sociotechnical perspective, technology, people, structure and processes must be optimized together.",
  why:"One of the biggest conceptual shifts, because earlier theories looked almost only inside the organization. What remains today: digital transformation, ecosystems, end-to-end processes and interdependencies.",
  sees:"Technology, people, structure and processes out of alignment.",
  rec:"Redesign the system as a whole instead of fixing one piece at a time.",
  blind:"Offers few simple prescriptions.",
  signals:["new technology → roles and skills change","fix one problem and another appears","interdependencies between departments","knock-on effects"],
  facts:["Bertalanffy was a biologist: the idea of the open system comes from living organisms, which constantly exchange energy with their environment.","Trist and Bamforth (1951) studied British coal mines. Mechanization with the longwall method broke up small self-regulating teams of miners, and absenteeism and problems increased. The “better” technology alone wasn’t enough."],
  vx:"Acquiring Red Hat (2019) means integrating technology, people and a very different open-source culture. What knock-on effects on processes, skills and collaboration?"},
 {id:"con",code:"CON",name:"Contingency",era:"~1960–1980",people:"Woodward · Burns & Stalker · Lawrence & Lorsch · Mintzberg",
  q:"Which structure fits which context?",
  idea:"There is no one best way to organize. The right structure depends on strategy, environment, technology, size, uncertainty and people’s capabilities. In a stable environment, hierarchy and standards can work; in a dynamic one, decentralization, teams and experimentation work better.",
  why:"Classical theories searched for the one best way, but empirical research found successful companies organized in very different ways. The message: good organizational design doesn’t copy best practices, it creates fit.",
  sees:"A structure that no longer fits a changed environment.",
  rec:"More flexibility, decentralization and cross-functional coordination where needed.",
  blind:"Power, politics and institutional pressures.",
  signals:["“it was right for the old world”","the market has become unpredictable","centralized vs decentralized","“it depends on…”"],
  facts:["Burns & Stalker (1961) studied Scottish firms moving into electronics. Mechanistic organizations (rigid, hierarchical) struggled to innovate; organic ones (fluid, networked) adapted better.","Joan Woodward compared about 100 firms in South Essex and found that effective structure depended on production technology: unit, mass or continuous-process production.","The name contingency theory comes from Lawrence & Lorsch (1967)."],
  vx:"In the 1990s the PC changed the market fast and IBM came close to disaster. Today cloud and AI markets move quickly: does the current structure create fit?"},
 {id:"eco",code:"ECO",name:"Economic",era:"~1970–1990",people:"Coase · Williamson · Jensen & Meckling",
  q:"Why do organizations exist, instead of just markets?",
  idea:"Transaction costs: the choice between buying on the market and doing it in-house depends on how costly the transactions are to coordinate. Agency theory: different actors have different interests, e.g. shareholders and management, so incentives, monitoring, governance and contracts are needed.",
  why:"If markets are efficient, why do huge companies with internal hierarchies exist? The boundaries of the organization needed explaining. What remains today: outsourcing, make-or-buy decisions, corporate governance and incentive systems.",
  sees:"Governance, incentives or organizational boundaries that create inefficiency.",
  rec:"Redesign incentives, contracts, monitoring or make-or-buy choices.",
  blind:"Culture, meaning, informal organization.",
  signals:["make or buy, outsourcing","bonuses and conflicts of interest","“the manager pursues their own interests”","contracts that are hard to write"],
  facts:["Coase published The Nature of the Firm in 1937, developing ideas from a study trip to the United States as a young man. He won the Nobel Prize in 1991.","Williamson won the Nobel Prize in 2009 together with Elinor Ostrom. His theory uses Simon’s bounded rationality: the lenses talk to each other.","Jensen & Meckling’s paper (1976) is among the most cited in the economics of the firm and helped spread executive pay tied to share value."],
  vx:"IBM sold its PC business to Lenovo (2005) and spun off Kyndryl (2021). Why redraw the company’s boundaries like this? And as a listed company, how does it manage the agency problem?"},
 {id:"ins",code:"INS",name:"Institutional",era:"~1970 →",people:"Meyer & Rowan · DiMaggio & Powell",
  q:"Why do organizations end up looking alike?",
  idea:"Efficiency doesn’t explain everything: organizations adopt practices because they are seen as legitimate, professional, expected. There are three pressures (isomorphism): coercive (laws and actors you depend on), normative (professions and experts) and mimetic (copying those who seem successful).",
  why:"Many organizations adopted structures that didn’t improve performance, and that needed explaining. Today the lens explains ESG, certifications, AI governance, sustainability and management fashions.",
  sees:"Practices adopted for legitimacy rather than performance.",
  rec:"Examine regulatory, professional and imitation pressures.",
  blind:"Internal efficiency and individual motivation.",
  signals:["“all our competitors do it”","investors or society expect it","a law requires it → coercive","doesn’t improve performance but is done anyway"],
  facts:["DiMaggio & Powell’s paper (1983) is titled The Iron Cage Revisited, a direct nod to Weber’s iron cage.","Meyer & Rowan (1977) describe formal structures as “myth and ceremony”. The official structure is often disconnected (decoupling) from how work actually gets done.","Imitation grows with uncertainty: when you don’t know what works, you copy whoever seems successful."],
  vx:"AI strategies, ESG, ethics boards: how much does IBM adopt for efficiency and how much for legitimacy, including with enterprise clients who expect these practices?"}
];
const QUIZ = [
 {id:"q1",lens:"ins",s:"A Swiss insurer launches an \"AI strategy\" and publishes an ESG report. Management admits neither improves performance, but all competitors do it and investors expect it.",a:"Which lens explains this behaviour best?",o:[
  ["Institutional theory","The motive is legitimacy and imitation, not efficiency. That’s mimetic isomorphism plus investors’ expectations.",1],
  ["Decision-making theory","There is a decision, but no sign of limited information or satisficing. The mere presence of a decision isn’t enough to pick this lens."],
  ["Classical theory","The classical lens explains practices adopted for efficiency, but here the company admits efficiency doesn’t improve."],
  ["Human Relations","Nothing about employee motivation, groups or recognition."]]},
 {id:"q2",lens:"con",s:"A manufacturer with highly specialized departments and a strict hierarchy was successful for decades. Now the market is unpredictable and customers want customized products. A consultant says: \"Your structure wasn't wrong. It fit the old world.\"",a:"Which lens is the consultant using, and what would Burns & Stalker suggest?",o:[
  ["Contingency: move toward a more organic structure","“It fit the old world” is about fit with context. Dynamic environment → organic structure: networks, less hierarchy, flexible roles.",1],
  ["Contingency: move toward a more mechanistic structure","Right lens, wrong direction: mechanistic structures work in stable environments."],
  ["Classical: clarify roles and add controls","More control in an unstable environment increases rigidity. That’s exactly the reflex the consultant is questioning."],
  ["Systems: the firm is a closed system","Systems are open by definition. And the consultant is talking about adapting to context, not internal interdependencies."]]},
 {id:"q3",lens:"dec",s:"At a logistics company every purchase above CHF 500 needs three approvals. Key data sits at headquarters, and regional managers often pick the first supplier that meets minimum criteria because they lack time to compare.",a:"Which lens gives the most direct diagnosis?",o:[
  ["Decision-making theory","Three signals of bounded rationality: information in the wrong place, bottlenecks and satisficing.",1],
  ["Classical theory","Approvals are a form of control, but the problem described is how information and decisions flow."],
  ["Economic theory","There’s no conflict of interest and no make-or-buy choice."],
  ["Contingency theory","Nothing about a changed environment or fit."]]},
 {id:"q4",lens:"sys",s:"A hospital introduces a new digital scheduling tool. Nurses who used to coordinate shifts informally must now follow the tool; handovers break down, overtime rises, and senior nurses feel their expertise no longer counts.",a:"Which lens best explains why the \"better\" technology made things worse?",o:[
  ["Sociotechnical systems theory","The technology changed without redesigning people, roles and coordination together. It’s the same pattern as Trist’s coal mines.",1],
  ["Human Relations","It captures the frustration, but not the mechanism: the problem comes from the interplay of technology, people and processes."],
  ["Classical theory","On the contrary: the classical lens would say more standardization is better."],
  ["Institutional theory","Nothing suggests the tool was adopted for legitimacy."]]},
 {id:"q5",lens:"eco",s:"A CEO's bonus depends on the quarterly share price. She cuts long-term R&D to boost short-term profit, against the interests of long-term shareholders.",a:"Which concept fits best?",o:[
  ["Agency theory","The agent’s (CEO’s) interests diverge from the principal’s (shareholders’). The typical response: redesign incentives and governance.",1],
  ["Transaction cost economics","Same theoretical family, but it’s about make or buy, not the principal–agent conflict."],
  ["Bounded rationality","She isn’t short of information: the choice is rational given her incentives."],
  ["Mimetic isomorphism","She isn’t copying anyone."]]},
 {id:"q6",lens:"eco",s:"A watch brand outsources cleaning and payroll but keeps movement design in-house, because that knowledge is highly specific and hard to protect in a contract.",a:"What explains where the company draws its boundary?",o:[
  ["Transaction cost economics","Standard activities are bought on the market; specific ones that are hard to contract stay in-house.",1],
  ["Contingency theory","It explains internal structure relative to the environment, not what to do in-house versus buy."],
  ["Agency theory","Same family, but the key concept here is transaction cost, not managers’ incentives."],
  ["Classical specialization","Specialization divides work inside the company. Here the question is where the company ends."]]},
 {id:"q7",lens:"cls",s:"A call center times every call, gives agents word-for-word scripts, and has managers redesign the process while agents only execute.",a:"Which organizational logic is this?",o:[
  ["Classical / scientific management","Divide, standardize, control, with planners separated from executors: pure Taylor.",1],
  ["Human Relations","The opposite: no attention to motivation or groups."],
  ["Contingency theory","There’s no discussion of fit with the environment."],
  ["Sociotechnical systems","It doesn’t optimize people and technology together: it only optimizes the task."]]},
 {id:"q8",lens:"hr",s:"A research team is moved into a highly visible pilot project. Pay stays the same, but managers ask for their opinions every week. Productivity rises, even in weeks when working conditions get slightly worse.",a:"What does this most resemble?",o:[
  ["The Hawthorne studies","Attention, participation and social dynamics matter more than physical conditions. That’s what surprised the Hawthorne researchers.",1],
  ["Scientific management","Taylor would look for the optimal method; here worse conditions don’t lower productivity."],
  ["Satisficing","There’s no decision made with limited information."],
  ["Normative isomorphism","There’s no external professional pressure."]]},
 {id:"q9",lens:"hr",s:"A manager believes employees avoid work unless controlled. He adds time tracking and tight supervision. Over time, employees show less initiative, which \"confirms\" his view.",a:"Which idea explains this cycle?",o:[
  ["McGregor's Theory X as a self-fulfilling assumption","Theory X is a manager’s assumption. The assumption becomes structure (control), and the structure produces the expected behaviour. Link it to Chapter 1!",1],
  ["Herzberg's hygiene factors","Herzberg separates hygiene factors and motivators. The core here is the self-fulfilling prophecy."],
  ["Agency theory","There is monitoring, but the cycle is driven by an assumption about people, not a conflict of interest."],
  ["Weber's bureaucracy","Weber describes formal, impersonal rules, not a cycle of expectations."]]},
 {id:"q10",lens:"hr",s:"After a salary increase, complaints at a design studio drop, but designers are no more engaged. Engagement rises only when they get more responsibility for client projects.",a:"Which theory fits best?",o:[
  ["Herzberg's two-factor theory","Salary is a hygiene factor: it removes dissatisfaction. Responsibility and recognition are the motivators.",1],
  ["Maslow's hierarchy of needs","Close, but the distinction between removing dissatisfaction and creating motivation is Herzberg’s."],
  ["Scientific management","Taylor would use pay as the main lever."],
  ["Contingency theory","The external environment isn’t involved."]]},
 {id:"q11",lens:"pol",s:"A company pays salaries, colleagues help each other without being asked, and part of the profit flows to a foundation that funds local projects.",a:"According to Polanyi, which statement is most accurate?",o:[
  ["Market exchange, reciprocity and redistribution coexist","Salary = market; spontaneous help = reciprocity; a foundation that collects and redistributes = redistribution. In reality the forms coexist.",1],
  ["It is pure market exchange, because it's a company","Trap: a company doesn’t live on market exchange alone."],
  ["Helping colleagues is redistribution","No centre collects and redistributes: it’s reciprocity."],
  ["The foundation is reciprocity","A centre that collects and allocates resources is redistribution."]]},
 {id:"q12",lens:"bel",s:"Mia is thirsty. She wants a specific Swiss mineral water and has the money for it, but she hasn't gone to a shop or expressed any intention to buy yet.",a:"At which stage is she?",o:[
  ["A want backed by purchasing power","A specific desire plus the means to pay. Demand only arises when she expresses the intention to buy.",1],
  ["Demand","Trap: there’s no expressed intention to buy from a supplier."],
  ["Only a need","It’s more than a need: the desire is specific and she can afford it."],
  ["Scarcity","Scarcity is an economic assumption, not a stage."]]},
 {id:"q13",lens:"bel",s:"A company's leadership fully accepts the assumption: \"Human needs are unlimited and resources are scarce.\"",a:"Which practice follows most directly from this assumption?",o:[
  ["Units compete for budgets and are measured by efficiency KPIs","Scarcity → competition, optimization, performance measurement, cost control.",1],
  ["Repair services and longer product lifecycles","That follows from the opposite assumption: sufficiency and sustainability."],
  ["Shared ownership and cooperation between units","That comes from an alternative assumption: cooperation can create more value than competition."],
  ["Choosing the first acceptable option","That’s satisficing (Simon), not a consequence of scarcity."]]},
 {id:"q14",lens:"ins",s:"After a new federal law, all hospitals in a canton set up the same kind of patient-data compliance office.",a:"Which form of isomorphism is this?",o:[
  ["Coercive","The pressure comes from laws and regulations.",1],
  ["Mimetic","They aren’t copying out of uncertainty: they’re required to."],
  ["Normative","The push doesn’t come from professional norms."],
  ["None, it's contingency fit","Contingency doesn’t explain why they all become the same."]]},
 {id:"q15",lens:"ins",s:"Most design management graduates learn design thinking at university. When they become managers, their companies run design thinking workshops, whether or not they improve results.",a:"Which institutional pressure is most visible?",o:[
  ["Normative","Education and professional networks spread “the right way” to work.",1],
  ["Coercive","No law requires it."],
  ["Mimetic","Maybe partly, but the source here is professional education."],
  ["It's Human Relations","A workshop isn’t in itself a motivation-based explanation."]]},
 {id:"q16",lens:"dec",s:"An insurer gives claims handlers clear rules for 90% of cases so they don't analyze every claim from scratch. Only unusual cases go to experts.",a:"Through the decision-making lens, why do such routines exist?",o:[
  ["They compensate for bounded rationality","Nobody can analyse everything: rules and routines reduce cognitive load. Simon sees them as decision support.",1],
  ["To control workers, as Taylor would","The similarity is superficial (there are rules), but the reason here is cognitive, not control."],
  ["To gain legitimacy","No sign of external expectations."],
  ["To reduce transaction costs with suppliers","There are no market transactions."]]},
 {id:"q17",lens:"cls",s:"In class, each lens was tested on Alpine Manufacturing: falling productivity, silos, slow decisions, and management reacting with more rules and reporting.",a:"What is the typical blind spot of the classical lens?",o:[
  ["Motivation, informal relationships and adaptation","It looks at the machine, not at people or a changing environment.",1],
  ["Efficiency and standardization","That’s exactly what it sees best."],
  ["Internal efficiency and individual motivation","That’s the institutional lens’s blind spot."],
  ["Power, politics and institutional pressures","That’s contingency’s blind spot."]]},
 {id:"q18",lens:"cls",s:"At Toyota, any worker can pull a cord to stop the production line when they spot a quality problem.",a:"Which element goes beyond classical thinking?",o:[
  ["Workers act as problem-solvers, not only executors","The classical lens separates thinkers from doers. Toyota gives workers authority and responsibility for quality.",1],
  ["Standardized work","Toyota standardizes a lot: this part is still classical."],
  ["Hierarchical control","That’s the opposite of what the cord does."],
  ["Measuring cycle times","Still classical logic."]]},
 {id:"q19",lens:"eco",vx:true,s:"Training case inspired by IBM: a large listed tech company sells its PC business and later spins off its infrastructure-services unit, to concentrate on hybrid cloud and AI.",a:"Which lens most directly asks where the boundaries of the firm should be?",o:[
  ["Economic theory (transaction costs, make-or-buy)","The economic lens asks what to keep in-house and what to leave to the market. Selling or spinning off a unit redraws the company’s boundaries.",1],
  ["Human Relations","It matters for the people involved, but it doesn’t explain the boundary choice."],
  ["Institutional theory","There may be a legitimacy push toward cloud and AI, but the boundary question is economic."],
  ["Classical theory","The classical lens organizes work within boundaries; it doesn’t decide where they go."]]},
 {id:"q20",lens:"pol",s:"A Swiss company keeps its apprenticeship programme and negotiates with unions, even though cheaper options exist abroad.",a:"Which Chapter 2 idea explains this best?",o:[
  ["Embeddedness","Economic choices are embedded in society’s norms, institutions and culture.",1],
  ["Market exchange","The market alone would suggest the cheapest option."],
  ["Scarcity assumption","That’s Chapter 1, and it would push toward efficiency."],
  ["Satisficing","That’s Chapter 3, the decision-making lens."]]}
];
const PAIRS = [
 {id:"p1",s:"“There’s no best way: it depends on the environment.”",a:"con",b:"sys",why:"“It depends” is the signature of contingency. Systems theory talks about interdependencies, not which structure to choose."},
 {id:"p2",s:"“We changed the software, and roles, skills and collaboration changed too.”",a:"sys",b:"con",why:"Knock-on effects between technology, people and processes: the sociotechnical perspective."},
 {id:"p3",s:"“We cut costs by standardizing every movement.”",a:"cls",b:"eco",why:"Efficiency through method and standards: Taylor. The economic lens would talk about transactions and incentives."},
 {id:"p4",s:"“We make it in-house, because a contract with a supplier would be too risky.”",a:"eco",b:"cls",why:"Make-or-buy and hard-to-write contracts: transaction costs (Williamson)."},
 {id:"p5",s:"“People stay because they feel they belong to the group.”",a:"hr",b:"ins",why:"Belonging and informal relationships explain behaviour: Human Relations."},
 {id:"p6",s:"“We’re introducing remote work because that’s what people expect from a modern employer.”",a:"ins",b:"hr",why:"The motive is external expectation, i.e. legitimacy, not motivation: institutional."},
 {id:"p7",s:"“The manager picks the first solution that meets the minimum criteria.”",a:"dec",b:"cls",why:"That’s the definition of satisficing (Simon)."},
 {id:"p8",s:"“The department head plans, the workers execute.”",a:"cls",b:"dec",why:"Separating planning from execution is a pillar of the classical lens."},
 {id:"p9",s:"“Shareholders fear the CEO is pursuing his own interests.”",a:"eco",b:"dec",why:"Principal–agent conflict: agency theory."},
 {id:"p10",s:"“Nobody has all the information, so we create routines.”",a:"dec",b:"eco",why:"Routines as a response to bounded rationality: the decision-making lens."},
 {id:"p11",s:"“We take resources and information from the environment and give them back transformed.”",a:"sys",b:"con",why:"Input → transformation → output: the definition of an open system."},
 {id:"p12",s:"“We’re small and the market is stable: staying centralized works for us.”",a:"con",b:"sys",why:"Size and environment determine the fitting structure: fit, so contingency."},
 {id:"p13",s:"“I pay taxes and the state funds public universities.”",a:"pol",b:"bel",why:"A centre collects and redistributes: redistribution (Polanyi, Ch. 2)."},
 {id:"p14",s:"“If we believe resources are scarce, of course departments compete.”",a:"bel",b:"pol",why:"An assumption that generates values and practices: the Chapter 1 chain."},
 {id:"p15",s:"“Raising salaries stopped the complaints, but didn’t motivate anyone.”",a:"hr",b:"eco",why:"Hygiene factors versus motivators: Herzberg. The economic lens would only see the incentive."},
 {id:"p16",s:"“Every hospital has the same compliance office because the law requires it.”",a:"ins",b:"cls",why:"Coercive isomorphism: organizations become similar under external regulatory pressure."}
];
const PEOPLE = {
 taylor:{name:"Frederick W. Taylor",dates:"1856–1915",lens:"cls",role:"American mechanical engineer, father of Scientific Management",
  world:"American steelworks in the late 19th century (Midvale Steel, Bethlehem Steel). Work was done by rule of thumb, and workers deliberately slowed down (soldiering) for fear of being paid less.",
  said:"Every task can be studied scientifically, with time and motion, to find the one best way. Management selects, trains and plans; the worker carries out the prescribed method and is paid with piece-rate incentives.",
  today:"Lean, KPIs, time tracking and so-called algorithmic management (think of delivery apps that measure every minute) are direct heirs of Taylor.",
  work:"The Principles of Scientific Management (1911)",
  fact:"His system was so controversial that after a strike at the Watertown Arsenal in 1911, a special committee of the US Congress investigated it with hearings.",
  confuse:"Fayol: Taylor looks at the company from the bottom up (the task on the shop floor), Fayol from the top down (the director’s job).",
  wiki:"Frederick_Winslow_Taylor"},
 fayol:{name:"Henri Fayol",dates:"1841–1925",lens:"cls",role:"French mining engineer, company director, father of Administrative Management",
  world:"For decades he was managing director of a French mining and metallurgy group (Commentry-Fourchambault), which he turned around from a difficult situation.",
  said:"Management is a universal activity that can be taught. It has five functions: planning, organizing, commanding, coordinating, controlling. He also proposed 14 principles, including division of work, unity of command, scalar chain and esprit de corps.",
  today:"Org charts, the chain of command and the “functions of management” in textbooks largely come from him.",
  work:"Administration industrielle et générale (1916)",
  fact:"For Fayol every employee should have only one boss (unity of command). Matrix structures, like IBM’s, openly break this principle: worth discussing in the project.",
  confuse:"Taylor: Fayol doesn’t time tasks, he describes what the people running the company should do.",
  wiki:"Henri_Fayol"},
 weber:{name:"Max Weber",dates:"1864–1920",lens:"cls",role:"German sociologist, economist and jurist, theorist of bureaucracy",
  world:"Germany industrializing and building a modern state. Weber asks what legitimate authority rests on and how society becomes “rational”.",
  said:"Authority can be traditional, charismatic or legal-rational. Bureaucracy (hierarchy, written rules, impersonality, officials chosen for competence) replaces favouritism and arbitrariness with rules that apply equally to everyone.",
  today:"Procedures, compliance, criteria-based hiring and written documentation. But also the criticism of “bureaucracy” slowing things down.",
  work:"Economy and Society (posthumous, 1922); The Protestant Ethic and the Spirit of Capitalism (1904–05)",
  fact:"He feared rationality would become a shell “hard as steel”, translated into English as iron cage. In 1983 DiMaggio & Powell titled their paper The Iron Cage Revisited.",
  confuse:"Taylor and Fayol: Weber looks neither at the task nor at the manager, but at the whole organization and the legitimacy of authority.",
  wiki:"Max_Weber"},
 mayo:{name:"Elton Mayo",dates:"1880–1949",lens:"hr",role:"Australian industrial psychologist and sociologist, Harvard Business School",
  world:"The 1920s and 30s: Taylorist factories, conflict between workers and management. Lighting, breaks and pay were thought to explain productivity.",
  said:"Workers are social beings. Informal groups, the need to belong, attention and recognition influence performance more than physical conditions. He became the face of the Hawthorne studies.",
  today:"Team culture, engagement, attention to informal groups and leadership.",
  work:"The Human Problems of an Industrial Civilization (1933)",
  fact:"The Hawthorne studies (Western Electric, near Chicago) began before he arrived. Today their data are heavily debated and the “Hawthorne effect” is contested by several reanalyses.",
  confuse:"Maslow: Mayo starts from factory observations of groups, Maslow from a psychological theory of individual needs.",
  wiki:"Elton_Mayo"},
 maslow:{name:"Abraham Maslow",dates:"1908–1970",lens:"hr",role:"American psychologist, founder of humanistic psychology",
  world:"Mid-20th-century psychology mainly studied pathologies and behaviour. Maslow wanted to understand what drives people to grow.",
  said:"Needs form a hierarchy: physiological, safety, belonging, esteem, self-actualization. Higher needs become motivating once lower ones are largely satisfied.",
  today:"Talk of purpose, personal growth and well-being at work. Widely used, but also criticized for weak empirical evidence.",
  work:"A Theory of Human Motivation (1943); Motivation and Personality (1954)",
  fact:"The famous pyramid isn’t Maslow’s: the graphic shape was popularized by other authors after him.",
  confuse:"Herzberg: Maslow has a ladder of needs; Herzberg splits factors into two separate groups (hygiene and motivators).",
  wiki:"Abraham_Maslow"},
 herzberg:{name:"Frederick Herzberg",dates:"1923–2000",lens:"hr",role:"American psychologist, two-factor theory",
  world:"Late 1950s: companies tried to motivate with better pay and conditions, with disappointing results.",
  said:"Satisfaction and dissatisfaction aren’t two ends of one scale. Hygiene factors (pay, conditions, policies, supervision) prevent dissatisfaction; motivators (achievement, recognition, responsibility, the work itself, growth) create motivation.",
  today:"Job enrichment: giving more responsibility and autonomy instead of only raising pay.",
  work:"The Motivation to Work (1959); “One More Time: How Do You Motivate Employees?” (Harvard Business Review, 1968)",
  fact:"The theory came from interviews with about 200 engineers and accountants in Pittsburgh, who were asked to describe times they felt especially good or bad at work.",
  confuse:"Maslow: for Herzberg the opposite of “satisfied” isn’t “dissatisfied”, but “not satisfied”.",
  wiki:"Frederick_Herzberg"},
 mcgregor:{name:"Douglas McGregor",dates:"1906–1964",lens:"hr",role:"Professor of management at MIT",
  world:"The 1950s: management still largely based on command and control, while psychology was painting a richer picture of people.",
  said:"Managers act on assumptions about people. Theory X: people avoid work and must be controlled. Theory Y: people seek responsibility if the context allows. Assumptions tend to become self-fulfilling.",
  today:"Trust, autonomy and hybrid work: every “control or trust” debate is X versus Y.",
  work:"The Human Side of Enterprise (1960)",
  fact:"Before returning to MIT he was president of Antioch College, an experience that put his ideas on leadership to the test.",
  confuse:"They aren’t two kinds of workers but two managerial worldviews. Direct link to Chapter 1: assumptions become structures.",
  wiki:"Douglas_McGregor"},
 simon:{name:"Herbert A. Simon",dates:"1916–2001",lens:"dec",role:"American economist, political scientist, cognitive psychologist and computer scientist",
  world:"Classical economics assumed a perfectly rational decision-maker. Simon studied real administrations and saw something quite different.",
  said:"Bounded rationality: information, time and cognitive capacity are limited. People choose the first good-enough option (satisficing), and organizations create routines and rules to support decisions.",
  today:"Decision rights, information systems, AI decision support: designing an organization means designing decisions.",
  work:"Administrative Behavior (1947); Organizations (1958, with March)",
  fact:"He won the Nobel Prize in Economics (1978) and the Turing Award (1975). With Allen Newell he created the Logic Theorist in 1956, one of the first artificial intelligence programs.",
  confuse:"Williamson uses Simon’s bounded rationality, but to explain the boundaries of the firm: that’s the economic lens.",
  wiki:"Herbert_A._Simon"},
 march:{name:"James G. March",dates:"1928–2018",lens:"dec",role:"Scholar of organizations and decisions, Stanford",
  world:"After Simon: if rationality is bounded, how do organizations really decide and learn?",
  said:"Organizations are coalitions with different goals that decide through routines and rules. In the garbage can model (1972, with Cohen and Olsen), problems, solutions and decision-makers meet almost by chance.",
  today:"Innovation and organizational learning: the dilemma between exploiting what you know and exploring the new.",
  work:"Organizations (1958, with Simon); A Behavioral Theory of the Firm (1963, with Cyert)",
  fact:"His 1991 article on exploration and exploitation is the basis for the concept of ambidexterity, which you’ll meet in Chapter 6. He also published poetry collections.",
  confuse:"Simon: March shifts the focus from the individual decision-maker to collective processes and learning.",
  wiki:"James_G._March"},
 bertalanffy:{name:"Ludwig von Bertalanffy",dates:"1901–1972",lens:"sys",role:"Austrian biologist, founder of general systems theory",
  world:"Early 20th-century biology: you can’t understand an organism by taking it apart piece by piece, because it lives through constant exchange with its environment.",
  said:"There are principles common to all systems: biological, social, technical. Open systems exchange energy and information with their environment, and the same result can be reached by different paths (equifinality).",
  today:"Systems thinking, ecosystems, digital transformation seen as a change of the whole system.",
  work:"General System Theory (1968)",
  fact:"He was a biologist, not a management theorist: organizations as “organisms” come from his ideas.",
  confuse:"Katz & Kahn: Bertalanffy creates the general theory, they apply it explicitly to organizations.",
  wiki:"Ludwig_von_Bertalanffy"},
 katzkahn:{name:"Daniel Katz & Robert L. Kahn",dates:"1903–1998 · 1918–2019",lens:"sys",role:"American social psychologists, University of Michigan",
  world:"The 1960s: organization studies looked almost only inside the company, as if it were a closed system.",
  said:"The organization is an open system: input from the environment, transformation (throughput), output returned. It survives only if this cycle keeps renewing.",
  today:"Thinking in value chains, end-to-end flows and dependencies on clients, suppliers and partners.",
  work:"The Social Psychology of Organizations (1966)",
  fact:"Robert Kahn lived to over 100: born in 1918, died in 2019.",
  confuse:"Contingency: both look at the environment, but systems theory explains interdependencies, contingency which structure to choose.",
  wiki:"Open_system_(systems_theory)"},
 tristemery:{name:"Eric Trist & Fred Emery",dates:"1909–1993 · 1925–1997",lens:"sys",role:"Researchers at the Tavistock Institute in London, sociotechnical theory",
  world:"Post-war Britain: new technologies in mines and factories promised productivity but often made things worse.",
  said:"The social system and the technical system must be designed together (joint optimization). Optimizing technology alone makes the whole system worse.",
  today:"Every software, automation or AI rollout that fails because nobody rethought roles and collaboration.",
  work:"Trist & Bamforth (1951) on coal mining; Emery & Trist, “The Causal Texture of Organizational Environments” (1965)",
  fact:"In 1965 they described “turbulent” environments, where everything changes at once: an idea that anticipates Chapter 6 on complexity.",
  confuse:"Human Relations: sociotechnical thinkers don’t just look at people, but at how people and technology fit together.",
  wiki:"Sociotechnical_system"},
 woodward:{name:"Joan Woodward",dates:"1916–1971",lens:"con",role:"British industrial sociologist",
  world:"The 1950s: people still believed in Fayol’s universal principles. Woodward wanted to test them with data.",
  said:"Studying about 100 firms in South Essex, she found that no universal principle predicted success. Successful firms had a structure suited to their technology: unit, mass or continuous-process production.",
  today:"The idea that technology (today digital and AI) changes which organizational structure fits best.",
  work:"Industrial Organization: Theory and Practice (1965)",
  fact:"She set out to confirm the classical principles and ended up dismantling them: a great example of separating assumption from evidence.",
  confuse:"Burns & Stalker: Woodward links structure to technology, Burns & Stalker to the market environment.",
  wiki:"Joan_Woodward"},
 burnsstalker:{name:"Tom Burns & G. M. Stalker",dates:"Burns 1913–2001",lens:"con",role:"Sociologist and psychologist, research in Scotland",
  world:"After the war, traditional Scottish firms tried to move into electronics, a new and very fast-changing industry.",
  said:"Mechanistic organizations (rigid roles, hierarchy, vertical communication) work in stable environments. Organic ones (fluid roles, networks, lateral communication) work in uncertain, innovative environments.",
  today:"The agile-versus-hierarchy debate and separate innovation units in large companies.",
  work:"The Management of Innovation (1961)",
  fact:"“Organic” doesn’t mean “better”: in a stable environment the mechanistic structure is the right choice. A common exam trap.",
  confuse:"Lawrence & Lorsch: Burns & Stalker compare whole firms; Lawrence & Lorsch show that different departments of the same firm need different structures.",
  wiki:"Mechanistic_and_organic_systems"},
 lawrencelorsch:{name:"Paul Lawrence & Jay Lorsch",dates:"1922–2011 · 1932–",lens:"con",role:"Professors at Harvard Business School",
  world:"The 1960s: large companies with very different departments (R&D, production, sales) that struggled to work together.",
  said:"The more uncertain the environment, the more departments differentiate (goals, time horizons, styles). So stronger integration mechanisms are needed to hold them together: differentiation and integration.",
  today:"Silos, coordinating roles, cross-functional teams, product managers as integrators.",
  work:"Organization and Environment (1967)",
  fact:"They coined the term contingency theory. They studied three industries with different levels of uncertainty: plastics, food and containers.",
  confuse:"Burns & Stalker: here the focus is the balance between differentiation and integration inside the company.",
  wiki:"Contingency_theory"},
 mintzberg:{name:"Henry Mintzberg",dates:"1939–",lens:"con",role:"Canadian management scholar, McGill University",
  world:"The 1970s: textbooks described the manager as a rational planner. Mintzberg went to observe what executives actually did.",
  said:"Organizations cluster into coherent configurations: simple structure, machine bureaucracy, professional bureaucracy, divisionalized form, adhocracy. Each works in a different context.",
  today:"Describing a real company’s structure, e.g. IBM’s divisions or a consultancy as an adhocracy.",
  work:"The Structuring of Organizations (1979); The Nature of Managerial Work (1973)",
  fact:"Observing CEOs, he found their work is fragmented: many short activities, constant interruptions, little time for reflection. He’s also a well-known critic of MBAs (Managers Not MBAs, 2004).",
  confuse:"Fayol: Fayol describes how managers should work, Mintzberg how they actually work.",
  wiki:"Henry_Mintzberg"},
 coase:{name:"Ronald Coase",dates:"1910–2013",lens:"eco",role:"British economist, University of Chicago",
  world:"The 1930s: economics explained markets well, but not why companies with internal hierarchies exist.",
  said:"Coordinating through the market has costs. When it pays off, internal authority replaces price: that’s why the firm exists, and its boundaries depend on these costs.",
  today:"Every make-or-buy decision and every outsourcing discussion.",
  work:"“The Nature of the Firm” (1937)",
  fact:"He won the Nobel Prize in 1991, more than 50 years after his most famous article, and lived to 102.",
  confuse:"Williamson: Coase asks the question, Williamson systematically develops transaction cost theory.",
  wiki:"Ronald_Coase"},
 williamson:{name:"Oliver E. Williamson",dates:"1932–2020",lens:"eco",role:"American economist, UC Berkeley",
  world:"The 1970s: large conglomerates, vertical integration and debate about why companies do certain activities in-house.",
  said:"Transaction Cost Economics: the choice between market and hierarchy depends on asset specificity, uncertainty and frequency. It starts from two assumptions: bounded rationality and opportunism.",
  today:"Outsourcing, strategic partnerships, platforms, vertical integration.",
  work:"Markets and Hierarchies (1975); The Economic Institutions of Capitalism (1985)",
  fact:"He trained at Carnegie, where Simon taught, and won the 2009 Nobel Prize together with Elinor Ostrom.",
  confuse:"Jensen & Meckling: Williamson explains the boundaries of the firm, they explain the conflict between owners and managers.",
  wiki:"Oliver_E._Williamson"},
 jensenmeckling:{name:"Michael C. Jensen & William H. Meckling",dates:"1939–2024 · 1921–1998",lens:"eco",role:"American financial economists",
  world:"The 1970s: large listed companies run by managers who don’t own them.",
  said:"Agency theory: the principal (shareholders) delegates to the agent (management), who may have different interests. This creates agency costs: monitoring, bonding and residual loss. Incentives and governance are needed.",
  today:"Stock options, performance bonuses, independent boards, shareholder value.",
  work:"“Theory of the Firm: Managerial Behavior, Agency Costs and Ownership Structure” (1976)",
  fact:"It’s one of the most cited articles in economics and finance. Its success helped spread pay tied to share prices, with effects that were later hotly debated.",
  confuse:"Coase and Williamson: same economic lens, but the topic here is incentives and conflicts of interest, not make-or-buy.",
  wiki:"Principal–agent_problem"},
 meyerrowan:{name:"John W. Meyer & Brian Rowan",dates:"Meyer 1935–",lens:"ins",role:"American sociologists, neo-institutionalism",
  world:"The 1970s: schools and public administrations adopted formal structures that nobody followed in daily practice.",
  said:"Formal structures are often “myth and ceremony”: they signal legitimacy to the outside. That’s why they can be disconnected (decoupling) from how work really gets done.",
  today:"Codes of ethics, certifications or strategies that exist on paper but change little in practice.",
  work:"“Institutionalized Organizations: Formal Structure as Myth and Ceremony” (1977)",
  fact:"Decoupling is a great word for the project: the gap between what a company communicates and what you find out in the Q&A.",
  confuse:"DiMaggio & Powell: Meyer & Rowan explain why structures are adopted for legitimacy, they explain why organizations become similar.",
  wiki:"Institutional_theory"},
 dimaggiopowell:{name:"Paul DiMaggio & Walter W. Powell",dates:"both 1951–",lens:"ins",role:"American sociologists",
  world:"The 1980s: organizations in the same field were increasingly alike, even when it brought no efficiency gains.",
  said:"Institutional isomorphism, with three mechanisms: coercive (laws and actors you depend on), mimetic (imitation under uncertainty), normative (professions, education, expert networks).",
  today:"ESG, AI strategies, agile methods, certifications: every “everybody’s doing it”.",
  work:"“The Iron Cage Revisited: Institutional Isomorphism and Collective Rationality in Organizational Fields” (1983)",
  fact:"The title echoes Weber’s iron cage: today the cage comes not from efficiency but from the pressure to resemble each other.",
  confuse:"Human Relations: normative pressure is about professions, not employee motivation.",
  wiki:"Institutional_isomorphism"},
 polanyi:{name:"Karl Polanyi",dates:"1886–1964",lens:"pol",role:"Economist, historian and economic anthropologist, born in Vienna, of Hungarian origin",
  world:"He lived through the 1929 crash, the rise of fascism and the war. He wanted to understand how faith in a self-regulating market had destabilized societies.",
  said:"The economy is embedded in society. Historically, economic integration happens through reciprocity, redistribution and market exchange. A market that dominates everything is a historical exception, not the norm.",
  today:"Debates about sustainability, welfare, the social economy and the role of business in society.",
  work:"The Great Transformation (1944)",
  fact:"His brother Michael Polanyi, a chemist and philosopher, introduced the concept of tacit knowledge, central to organizational learning in Chapter 7.",
  confuse:"Institutional lens: Polanyi talks about society containing the economy, neo-institutionalists about specific pressures on organizations in the same field.",
  wiki:"Karl_Polanyi"}
};
const LESSON = [
 {id:"s1",part:"Kick-off",slides:"9–12",title:"What Joël expects, and the AI rule",
  brief:"The expectations: active participation, critical thinking, collaboration, independent research, hands-on learning, constructive feedback, consistent attendance. On AI there’s one rule: it should support your thinking, not replace it.",
  hook:"For the project this counts double: an invented or unverified fact about IBM from AI doesn’t count as evidence.",
  ex:"Yes: having Williamson explained, generating questions, suggesting possible lenses, structuring ideas, improving language. No: generating the final diagnosis, inventing facts about IBM, replacing source research, outsourcing your interpretation of theory.",
  q:"Can you ask AI to summarize an IBM report you haven’t read and cite the summary as a source?",
  a:"No. AI may only summarize material you’ve already verified, and the summary isn’t evidence: the source is still the report."},
 {id:"s2",part:"Kick-off",slides:"13",title:"The course map: 7 chapters, 3 phases",
  brief:"Foundations & Context (Ch. 1–3: beliefs, economy, theories). Organizational Basics (Ch. 4–5: purpose, stakeholders, structure, processes). Systems & Adaptation (Ch. 6–7: complexity, people, culture, learning).",
  hook:"The course moves from why organizations exist, to how they work, to how they survive in a changing world.",
  ex:"For IBM: Ch. 1–3 give you the lenses, Ch. 4–5 what to observe (purpose, roles, decision rights), Ch. 6–7 the most interesting tensions to discuss.",
  q:"Which chapter covers “decision rights” and “handovers”?",
  a:"Chapter 5, Work, Structures & Processes: tasks, roles and decision rights; processes, coordination and handovers."},
 {id:"s3",part:"Kick-off",slides:"15–18",title:"The mission: diagnose, with incomplete information",
  brief:"You’re in the Organizational Design department and the Head of Strategy asks for an independent diagnosis: how does the organization work today, why might it be organized this way, where could it improve? Four steps: Prepare (desk research), Investigate (Q&A), Interpret (patterns and tensions), Diagnose & Recommend.",
  hook:"Evidence has four labels: FACT (public source), FINDING (from the Q&A), INTERPRETATION (conclusion via theory), ASSUMPTION (what you believe, with incomplete information).",
  ex:"A constructed example, not to reuse as is. FACT: IBM acquired Red Hat in 2019. FINDING: “Red Hat keeps its own processes” (hypothetical Q&A answer). INTERPRETATION: through the sociotechnical lens, light integration avoids breaking a system that works. ASSUMPTION: there are probably cultural tensions between the two worlds.",
  q:"“IBM is slow because it’s big”: what kind of statement is this?",
  a:"An ASSUMPTION. To become a diagnosis it needs facts (e.g. decision times), a finding from the Q&A and a lens that explains the mechanism (e.g. decision-making or contingency)."},
 {id:"s4",part:"Kick-off",slides:"20–23",title:"What the project must include",
  brief:"Minimum requirements: Purpose & Context; Structure & Processes; at least three theoretical lenses; People, Culture & Learning; Fit & Trade-offs; one or two realistic recommendations with benefits and risks. A 15-minute presentation with one coherent story, depth over breadth.",
  hook:"The key message: your job is to diagnose, not describe. Good analysis doesn’t pretend to know everything; it makes uncertainty visible.",
  ex:"A wasted Q&A question: “How many employees does IBM have?” (it’s online). A useful one: “When a project involves both cloud and consulting, who has the final say?”",
  q:"Why is opening the presentation with IBM’s history since 1911 a bad idea?",
  a:"It’s description. History only helps if it explains a pattern today; in 15 minutes what counts is a coherent diagnosis."},
 {id:"s5",part:"Kick-off",slides:"26–27",title:"How the exam works",
  brief:"It assesses key concepts, theoretical perspectives, recognizing concepts in situations, implications and trade-offs. Format: multiple choice, single choice, scenarios, short case.",
  hook:"The slide’s advice: don’t only memorize definitions; ask what each concept explains, connect it to real situations, know benefits, limits and trade-offs.",
  ex:"That’s exactly why this page has Detective and Pairs: they train recognition, not repetition.",
  q:"What question sums up the exam?",
  a:"Can you understand and apply organizational theory on your own?"},
 {id:"s6",part:"Ch. 1",slides:"30",title:"What is an organization?",
  brief:"Before any theory, the lecturer asks for your idea: draw it, write it, ask questions, build a map.",
  hook:"Every Chapter 3 theory answers this same question differently. Come back here at the end.",
  ex:"Try writing one sentence now, before you move on.",
  q:"How would three different lenses answer?",
  a:"Classical: a machine designed for efficiency. Human Relations: a network of people and relationships. Economic: an alternative to the market for coordinating transactions. None is wrong; each sees something."},
 {id:"s7",part:"Ch. 1",slides:"32",title:"Need → want → demand",
  brief:"A need arises from a perceived deficiency. When it becomes a specific desire you can afford, it’s a want backed by purchasing power. It becomes demand only when you express the intention to buy from a supplier.",
  hook:"It looks trivial, but it’s a precise chain, and a perfect trap for a multiple-choice question.",
  ex:"A company feels it lacks organized data (need). It wants a specific cloud solution and has the budget (want backed by purchasing power). It asks IBM for a quote (demand).",
  q:"You’re thirsty, you want a Rivella and you have 3 francs in your pocket. Is that demand?",
  a:"Not yet: it’s a want backed by purchasing power. It becomes demand when you express the intention to buy, e.g. at the counter."},
 {id:"s8",part:"Ch. 1",slides:"33–34",title:"Scarcity and the assumptions it carries",
  brief:"Scarcity: resources are finite, so only a limited amount of goods can be produced. It’s seen as the starting point of economics, and it carries assumptions: needs are unlimited, scarcity must be overcome through division of labour and exchange, we compete for scarce goods, the market is the best form, the best performers prevail.",
  hook:"Note the word “assumptions”: the lecturer isn’t saying they’re true or false, but that they are beliefs with consequences.",
  ex:"“Resources are finite” is close to a fact. “The market is the best form of organization” is a value assumption.",
  q:"Why does telling fact from assumption matter for the project too?",
  a:"It’s the same skill as FACT versus ASSUMPTION: the grade rewards those who separate what they know from what they believe."},
 {id:"s9",part:"Ch. 1",slides:"35–37",title:"What follows from what we believe",
  brief:"The consequences of scarcity at three levels. Individual: competition, accumulation, comparison, optimization. Organizational: efficiency targets, specialization, performance measurement, competition between units, cost control. Economic: markets, prices as allocation mechanisms, growth orientation.",
  hook:"The takeaway: assumptions influence values, values influence decisions, and repeated decisions shape organizations.",
  ex:"KPIs, competing budgets and cost control in a large company aren’t “natural”: they’re scarcity turned into structure.",
  q:"Who benefits from the logic of scarcity, and what problems can it create?",
  a:"Those already strong in competition benefit. Possible problems: inequality, overuse of resources, internal competition that destroys collaboration. There’s no single answer: the reasoning is what counts."},
 {id:"s10",part:"Ch. 1",slides:"38–41",title:"Reverse the assumption",
  brief:"Choose an alternative assumption and complete the chain: assumption → values → behaviour → organizational practices → coordination system. Example: “well-being doesn’t require unlimited consumption” → sufficiency and sustainability → sharing and repairing → circular business models, repair services, shared ownership → market + cooperation + redistribution.",
  hook:"Different assumptions produce different organizational realities. For any problem, ask what we’re assuming about people, needs, competition, value, success, growth.",
  ex:"It works great in the project: what assumption about growth and innovation lies behind IBM’s choices?",
  q:"Complete the chain for “cooperation can create more value than competition”.",
  a:"Values: trust, sharing. Behaviours: helping each other, exchanging knowledge. Practices: team goals and bonuses, partnerships, communities of practice. Coordination: more reciprocity alongside the market."},
 {id:"s11",part:"Ch. 2",slides:"43–44",title:"The economy is inside society (Polanyi)",
  brief:"The economy is the set of institutions and actions that serve to satisfy needs, and it depends on culture, values, education, technology, history, politics, law and natural resources. For Karl Polanyi, economic activity is embedded in society.",
  hook:"The consequence for organizations: they aren’t closed systems. This idea returns with systems theory.",
  ex:"IBM in Switzerland, India or the US follows different labour laws, cultures and expectations, even with the same global strategy.",
  q:"Why isn’t the org chart enough to understand a company?",
  a:"Because structure, processes and decisions are shaped by the norms, institutions, politics and culture of the environment the company is embedded in."},
 {id:"s12",part:"Ch. 2",slides:"45–48",title:"Three ways things circulate",
  brief:"Reciprocity: giving and receiving through relationships and mutual obligation (“I help you, one day someone will help me”). Redistribution: a centre collects and redistributes (taxes, temple, state). Market exchange: money, prices, contracts (“I pay for what I want”).",
  hook:"Society ⊃ economy ⊃ organizations: to understand an organization you have to build a bridge to its environment.",
  ex:"Inside a company: salary is market, the central budget allocated to departments is redistribution, the colleague who helps you unasked is reciprocity.",
  q:"A team receives its annual budget from headquarters. Which form is that?",
  a:"Redistribution: a centre collects resources and decides how to allocate them."},
 {id:"s13",part:"Ch. 2",slides:"49–51",title:"Exercise: where does exchange really happen?",type:"sort",
  brief:"The class exercise, now interactive. Choose the form for each example.",
  hook:"The slide’s lesson: the categories aren’t always clear-cut, and several logics coexist. Real economies rarely use only one mechanism.",
  items:[["Buying coffee at a café","M"],["Paying taxes","R"],["A friend helps you move apartment","C"],["Receiving unemployment benefits","R"],["Parents caring for their children","C"],["Buying a used bicycle online","M"],["A company pays an employee a salary","M"],["Neighbours share tools","C"],["Public university education","R"],["Employees help colleagues without being asked","C"]]},
 {id:"s14",part:"Ch. 3",slides:"53–54",title:"A century of questions about organizations",type:"timeline",
  brief:"Each era asked a new question, because the world of organizations had changed. The theories don’t cancel each other out: they add up.",
  hook:"The trick to remembering them: each lens answers the limits of the one before.",
  q:"What is the big shift in question between the classical lens and contingency?",
  a:"From “what is the best way to organize?” to “there is no best way: it depends on the context”."},
 {id:"s15",part:"Ch. 3",slides:"55–58",lens:"cls",title:"Classical: making the factory run",
  brief:"With industrialization, organizations grow and work has to be divided, standardized and coordinated at scale. Typical design: clear hierarchy, division of labour, formal roles and rules, standard processes; management plans and controls, employees execute.",
  hook:"Divide → Specialize → Standardize → Control → Optimize. Structure allows scale, but too much control makes you rigid.",
  ex:"From the Toyota video: standardized work and measuring times are still classical logic. But workers can stop the line and improve the process: they think, they don’t just execute.",
  q:"What remains of the classical lens today?",
  a:"Job descriptions, org charts, SOPs and standard processes, KPIs, hierarchical accountability."},
 {id:"s16",part:"Ch. 3",slides:"59–62",lens:"hr",title:"Human Relations: there are people inside the machine",
  brief:"Classical theory treated employees as parts of the production system. Mayo, Maslow, Herzberg and McGregor ask what happens when you consider the human and social side.",
  hook:"People are motivated by more than money, informal groups influence performance, and management’s assumptions shape how the organization is designed.",
  ex:"Today: engagement, team development, leadership development, psychological safety, employee experience, culture.",
  q:"What does this lens add to the classical one, in one sentence?",
  a:"Organizations aren’t only structures and processes, they are also networks of people and relationships."},
 {id:"s17",part:"Ch. 3",slides:"63–65",lens:"dec",title:"Decision-making: nobody knows everything",
  brief:"Earlier theories assumed managers could find the best solution. Simon challenges this: incomplete information, limited alternatives, limited time and cognitive capacity. People choose a good-enough solution (satisficing), and organizations create rules and routines to support decisions.",
  hook:"Organizational design is also decision design: who gets which information, and who is allowed to decide what?",
  ex:"Perfect rationality: all information and all alternatives → optimal decision. Bounded rationality: incomplete information → satisfactory decision.",
  q:"What does satisficing mean?",
  a:"Choosing the first option that meets an acceptable threshold, instead of searching indefinitely for the optimal one."},
 {id:"s18",part:"Ch. 3",slides:"66–67",lens:"sys",title:"Systems: everything is connected",
  brief:"One of the biggest conceptual shifts. Before, people looked mainly inside the organization; now the question is how it interacts with its environment. The sociotechnical perspective: technology, people, structure and processes must be optimized together.",
  hook:"New technology → processes change → jobs change → skills change → collaboration changes → structure changes.",
  ex:"Introducing generative AI in a company like IBM isn’t an IT project: it’s a change in roles, skills and coordination.",
  q:"What remains of the systems lens today?",
  a:"Digital transformation, organizational ecosystems, systems thinking, end-to-end processes, interdependencies."},
 {id:"s19",part:"Ch. 3",slides:"68–69",lens:"con",title:"Contingency: it depends",
  brief:"The classical lens searched for the best way to organize; contingency answers that there isn’t one. The right design depends on strategy, environment, technology, size, uncertainty, people and capabilities.",
  hook:"Good organizational design doesn’t copy best practices: it creates fit.",
  ex:"Stable environment: hierarchy, specialization and standards may work well. Dynamic environment: decentralization, teams and experimentation work better.",
  q:"Name two current debates that are pure contingency.",
  a:"Agile vs hierarchical, centralized vs decentralized, functional vs product structures, remote vs office, start-up vs corporate."},
 {id:"s20",part:"Ch. 3",slides:"70–71",lens:"eco",title:"Economic: why isn’t everything a market?",
  brief:"Transaction Cost Economics: sometimes buying on the market is efficient, sometimes it’s better to bring the activity inside the organization, depending on coordination costs. Agency Theory: different actors have different interests (shareholders and management), so incentives, monitoring, governance and contracts are needed.",
  hook:"Organizational boundaries and governance partly exist to manage transactions, incentives and conflicting interests.",
  ex:"Today: outsourcing, strategic partnerships, corporate governance, incentive systems, platforms, make-or-buy decisions.",
  q:"What is the underlying question of this lens?",
  a:"Why do organizations exist at all, instead of coordinating everything through markets?"},
 {id:"s21",part:"Ch. 3",slides:"72–73",lens:"ins",title:"Institutional: being legitimate",
  brief:"Efficiency doesn’t explain every decision. Sometimes practices are adopted because they’re seen as legitimate, professional, expected, socially acceptable. There are three pressures: regulation, professional norms, imitation (institutional isomorphism).",
  hook:"Organizations seek not only efficiency, they also seek legitimacy.",
  ex:"Why does everyone adopt sustainability reports, diversity policies, agile methods, AI strategies, compliance departments?",
  q:"Why do organizations in the same field become increasingly similar?",
  a:"Because of regulatory pressure (laws), normative pressure (professions and experts) and mimetic pressure (copying those who seem successful)."},
 {id:"s22",part:"Ch. 3",slides:"76–81",title:"Theory Detective: Alpine Manufacturing",type:"detective",
  brief:"A Swiss industrial company with 800 employees. Over the last two years:",
  facts:["productivity has declined","employee turnover has increased","decisions take too long","departments increasingly work in silos","customers expect faster customization","competitors are introducing new digital technologies","management has responded with more rules and reporting"],
  hook:"This is the exam format, and the project’s. Pick a lens: what problem does it see, what does it recommend, what does it miss?",
  q:"After trying every lens: why is management’s response (more rules) probably wrong?",
  a:"It’s a purely classical response to a problem that several lenses read as lack of fit (contingency), motivation (HR), decision bottlenecks (decision-making) and technological misalignment (systems). More control risks worsening silos, slowness and turnover."},
 {id:"s23",part:"Closing",slides:"82–83",title:"A modern organization is all of this at once",
  brief:"The legacy of the industrial age (hierarchy, centralized planning, functional division of labour, standardization, budgets and control) worked because of efficiency, predictability and scalability. It struggles with uncertainty, rapid change, innovation and cross-functional work.",
  hook:"There is no single correct diagnosis: each theory asks a different question.",
  ex:"A modern organization is at the same time a machine, a social system, a decision system, an open system, a contingent system, an economic system and an institutional actor.",
  q:"Match each metaphor to its lens and the need it expresses.",
  a:"Machine → classical: processes need efficiency. Social system → HR: people need to collaborate. Decision system → decision-making: information must become decisions. Open system → systems: it depends on its environment. Contingent system → contingency: structure must fit context. Economic system → economic: incentives and transactions matter. Institutional actor → institutional: legitimacy and societal expectations matter."},
 {id:"s24",part:"Closing",slides:"85–86",title:"What the next classes will look like",
  brief:"Each class: welcome and recap; each group presents its progress in 5 minutes (work done, key learnings, help needed); feedback and group learning; lecture with exercises and reflection; optional inputs or self-study.",
  hook:"To do for 30.09: start studying for the exam, start desk research, get familiar with the company, collect first observations.",
  ex:"For Group 2: arrive with first observations on IBM’s purpose, stakeholders, structure and processes, already labelled as FACT or ASSUMPTION.",
  q:"What does your group bring to the 5-minute update?",
  a:"Work done, key learnings, help needed."}
];
const ERAS=[["1900s","cls","How can work be organized efficiently?"],["1930s","hr","What role do people, motivation and relationships play?"],["1940s","dec","How do people and organizations actually make decisions?"],["1950s","sys","How does the organization interact with its environment?"],["1960s","con","Which design fits which situation?"],["1970s →","eco","Why do organizations choose certain arrangements? (economic)"],["1970s →","ins","Why do organizations become similar? (institutional)"]];
OSP.en={UI,LENSES,QUIZ,PAIRS,PEOPLE,LESSON,ERAS};
})();
