window.OSP=window.OSP||{};
(function(){
const LENSES = [
 {id:"bel",code:"C1",found:true,name:"Credenze e valori",era:"Cap. 1",people:"Bisogni · Scarsità · Valori",
  q:"Cosa diamo per scontato su persone, bisogni e valore?",
  idea:"Le organizzazioni nascono da assunzioni. La catena è: assunzioni → valori → decisioni → decisioni ripetute → strutture. Esempio: \"i bisogni sono illimitati e le risorse scarse\" produce competizione, ottimizzazione, KPI e mercato come forma ideale.",
  why:"Serve a vedere che competizione, crescita ed efficienza non sono leggi di natura, ma conseguenze di un'assunzione. Cambia l'assunzione (es. \"il benessere non richiede consumo illimitato\") e ottieni pratiche diverse: riparazione, cicli di vita lunghi, proprietà condivisa.",
  sees:"Le premesse nascoste dietro strutture e pratiche.",
  rec:"Rendere esplicita l'assunzione e chiedersi: cosa cambierebbe se credessimo il contrario?",
  blind:"Da sola non dice come progettare ruoli, processi e struttura concreta.",
  signals:["\"È naturale che i reparti competano\"","bisogno → want → domanda","crescita ed efficienza come valori indiscussi","assunzione alternativa: sufficienza, cooperazione"],
  facts:["Trappola classica: bisogno = carenza percepita; want backed by purchasing power = desiderio specifico + soldi per permetterselo; domanda = solo quando esprimi l'intenzione di comprare da un fornitore. Volere e poterselo permettere non è ancora domanda.","La domanda di chiusura del docente vale per tutto il corso: cosa assumiamo su persone, bisogni, scarsità, competizione, cooperazione, valore, successo, proprietà, crescita?"],
  vx:"IBM si definisce un'azienda di hybrid cloud e AI. Quali assunzioni su crescita, innovazione e persone emergono da come si racconta? Crescita, leadership tecnologica, reinvenzione continua?"},
 {id:"pol",code:"C2",found:true,name:"Polanyi ed embeddedness",era:"Cap. 2 · 1944",people:"Karl Polanyi (1886–1964)",
  q:"In quale società è immersa l'economia, e l'organizzazione?",
  idea:"L'economia è un processo sociale: la società contiene l'economia, che contiene le organizzazioni. Tre forme di integrazione: reciprocità (\"ti aiuto, un giorno qualcuno aiuterà me\"), redistribuzione (un centro raccoglie e distribuisce) e scambio di mercato (\"pago per ciò che voglio\").",
  why:"Polanyi voleva mostrare che il mercato autoregolato è una costruzione storica, non uno stato naturale. Per le organizzazioni vuol dire: non sono sistemi chiusi, e norme, cultura, politica e leggi entrano nelle loro decisioni.",
  sees:"Il contesto sociale, culturale e istituzionale dietro le scelte economiche.",
  rec:"Per capire un'organizzazione, studia il suo ambiente: leggi, cultura, relazioni, istituzioni.",
  blind:"Dice poco sulla struttura interna: ruoli, processi, diritti decisionali.",
  signals:["favori e aiuto senza prezzo → reciprocità","tasse, budget centrale, welfare → redistribuzione","prezzo, contratto, salario → mercato","\"le tre forme convivono\""],
  facts:["In The Great Transformation (1944) Polanyi chiama lavoro, terra e denaro \"merci fittizie\": non sono prodotti per essere venduti, eppure il mercato li tratta come merci.","Esercizio del corso: il salario è mercato, ma i colleghi che si aiutano senza che nessuno lo chieda sono reciprocità, e l'università pubblica è redistribuzione. Un'azienda reale usa quasi sempre più forme insieme."],
  vx:"IBM opera in più di 170 paesi: come cambiano le sue pratiche tra contesti culturali e legali diversi? Dove vedi mercato (clienti), redistribuzione (budget interni) e reciprocità (open source, community)?"},
 {id:"cls",code:"CLS",name:"Classica",era:"~1900–1930",people:"Taylor · Fayol · Weber",
  q:"Come rendere il lavoro efficiente e prevedibile?",
  idea:"L'organizzazione si progetta come una macchina: gerarchia chiara, divisione del lavoro, ruoli e regole formali, processi standard. Il management pianifica e controlla, i dipendenti eseguono. Logica: dividere → specializzare → standardizzare → controllare → ottimizzare.",
  why:"L'industrializzazione creava fabbriche enormi che crescevano in fretta. Il problema del tempo era coordinare migliaia di persone su larga scala in modo prevedibile. Oggi ne restano job description, organigrammi, SOP e KPI.",
  sees:"Inefficienza, ruoli poco chiari, poca standardizzazione e controllo.",
  rec:"Chiarire i ruoli, ottimizzare i processi, rafforzare responsabilità e standard.",
  blind:"Motivazione, relazioni informali, adattamento al cambiamento.",
  signals:["cronometro, script, procedure standard","chi pianifica ≠ chi esegue","più regole e reporting come risposta","organigramma e catena di comando"],
  facts:["Alla Bethlehem Steel Taylor studiò il carico dei lingotti di ghisa. Nel suo racconto, un operaio passò da circa 12,5 a 47 tonnellate al giorno seguendo un metodo prescritto al secondo.","Fayol era un ingegnere minerario diventato direttore d'azienda. Descrisse le funzioni del management: prevedere, organizzare, comandare, coordinare, controllare.","Weber vedeva la burocrazia come razionale, ma avvertiva che poteva diventare un guscio \"duro come l'acciaio\". In inglese è diventato il famoso iron cage."],
  vx:"Negli anni '60 IBM era il simbolo della grande impresa gerarchica e standardizzata. Cosa resta oggi di quella logica (processi globali, KPI, compliance)? E dove frena?"},
 {id:"hr",code:"HR",name:"Human Relations",era:"~1930–1960",people:"Mayo · Maslow · Herzberg · McGregor",
  q:"Che ruolo hanno persone, motivazione e relazioni?",
  idea:"Le persone non sono pezzi di un sistema produttivo. Le motiva più del denaro: riconoscimento, appartenenza, lavoro significativo. I gruppi informali influenzano la performance, lo stile di leadership conta, e le assunzioni del management sulle persone modellano l'organizzazione.",
  why:"La lente classica non riusciva a spiegare certi risultati: a Hawthorne la produttività cambiava per ragioni sociali, non tecniche. Oggi ne restano engagement, team development, psychological safety ed employee experience.",
  sees:"Bassa motivazione, relazioni deboli, cattiva esperienza dei dipendenti.",
  rec:"Partecipazione, sviluppo della leadership, riconoscimento, comunicazione, lavoro di squadra.",
  blind:"Inefficienze strutturali e ambiente esterno.",
  signals:["attenzione, riconoscimento, appartenenza","\"la paga non basta\"","il gruppo informale decide il ritmo","il manager pensa che i dipendenti siano pigri"],
  facts:["Hawthorne Works, Western Electric, vicino a Chicago, anni '20: la produttività saliva sia aumentando sia riducendo la luce. Il nome \"effetto Hawthorne\" arrivò solo nel 1958, da Henry Landsberger.","La famosa piramide non fu disegnata da Maslow: la forma a piramide venne diffusa da altri autori dopo di lui.","Herzberg: lo stipendio è un fattore igienico. Se è insufficiente crea insoddisfazione, ma aumentarlo non crea vera motivazione; quella viene da responsabilità, riconoscimento e crescita.","McGregor (1960): Theory X e Theory Y non sono due tipi di lavoratori, ma due insiemi di assunzioni dei manager, che tendono ad autoavverarsi."],
  vx:"Il motto THINK risale a Thomas J. Watson Sr. Come si traduce oggi la cultura IBM per decine di migliaia di dipendenti in remoto o ibrido? È un'ottima area per la Q&A."},
 {id:"dec",code:"DEC",name:"Decisionale",era:"~1940–1960",people:"Herbert Simon · James March",
  q:"Come si decide davvero, con informazioni limitate?",
  idea:"Razionalità limitata: nessuno ha informazioni complete, tempo illimitato e capacità cognitiva infinita. Quindi si semplifica, si valutano poche alternative e si sceglie la prima soluzione accettabile (satisficing). Le organizzazioni creano regole, routine e strutture per sostenere le decisioni.",
  why:"Le teorie precedenti presupponevano un manager capace di trovare la soluzione ottimale. Simon mostrò che è un'illusione. Da qui una conseguenza per il design: progettare un'organizzazione è anche progettare le decisioni, cioè chi riceve quali informazioni e chi può decidere cosa.",
  sees:"Informazioni e autorità mal distribuite, troppe approvazioni, colli di bottiglia.",
  rec:"Chiarire i diritti decisionali, migliorare il flusso di informazioni, ridurre i colli di bottiglia.",
  blind:"Cultura, ambiente esterno, fattori emotivi.",
  signals:["informazioni incomplete o nel posto sbagliato","\"la prima opzione accettabile\"","troppi livelli di approvazione","routine per non analizzare ogni caso"],
  facts:["Herbert Simon vinse il Nobel per l'economia (1978) e anche il Turing Award (1975): fu uno dei pionieri dell'intelligenza artificiale.","Satisficing è una parola inventata da Simon, fondendo satisfy e suffice.","March, con Cohen e Olsen, propose il garbage can model (1972): nelle organizzazioni problemi, soluzioni e decisori a volte si incontrano quasi per caso."],
  vx:"In un'organizzazione globale a matrice, chi decide cosa tra paesi, linee di business e funzioni? Dove nascono i colli di bottiglia? Domanda perfetta per la Q&A."},
 {id:"sys",code:"SYS",name:"Sistemi e sociotecnica",era:"~1950–1970",people:"Bertalanffy · Katz & Kahn · Trist & Emery",
  q:"Come interagisce l'organizzazione con il suo ambiente?",
  idea:"Tutto è interconnesso: cambi una parte e ne influenzi molte altre. L'organizzazione è un sistema aperto che prende risorse dall'ambiente, le trasforma e le restituisce. Secondo la prospettiva sociotecnica, tecnologia, persone, struttura e processi vanno ottimizzati insieme.",
  why:"È uno dei cambi concettuali più grandi, perché le teorie precedenti guardavano quasi solo dentro l'organizzazione. Oggi ne restano digital transformation, ecosistemi, processi end-to-end e interdipendenze.",
  sees:"Tecnologia, persone, struttura e processi non allineati tra loro.",
  rec:"Riprogettare il sistema insieme invece di aggiustare un pezzo alla volta.",
  blind:"Offre poche prescrizioni semplici.",
  signals:["nuova tecnologia → cambiano ruoli e competenze","risolvi un problema e ne nasce un altro","dipendenze tra reparti","effetti a catena"],
  facts:["Bertalanffy era un biologo: l'idea di sistema aperto viene dagli organismi viventi, che scambiano continuamente energia con l'ambiente.","Trist e Bamforth (1951) studiarono le miniere di carbone britanniche. La meccanizzazione con il metodo longwall spezzò i piccoli gruppi autoregolati di minatori, e assenteismo e problemi aumentarono. La tecnologia \"migliore\" da sola non bastava."],
  vx:"Acquisire Red Hat (2019) significa integrare tecnologia, persone e una cultura open source molto diversa. Quali effetti a catena su processi, competenze e collaborazione?"},
 {id:"con",code:"CON",name:"Contingency",era:"~1960–1980",people:"Woodward · Burns & Stalker · Lawrence & Lorsch · Mintzberg",
  q:"Quale struttura si adatta a quale contesto?",
  idea:"Non esiste un modo migliore di organizzarsi. La struttura giusta dipende da strategia, ambiente, tecnologia, dimensione, incertezza e capacità delle persone. In un ambiente stabile possono funzionare gerarchia e standard; in uno dinamico funzionano meglio decentramento, team e sperimentazione.",
  why:"Le teorie classiche cercavano la one best way, ma le ricerche empiriche mostrarono aziende di successo organizzate in modi molto diversi. Il messaggio: un buon design organizzativo non copia le best practice, crea fit.",
  sees:"Una struttura che non si adatta più a un ambiente cambiato.",
  rec:"Più flessibilità, decentramento e coordinamento cross-funzionale dove serve.",
  blind:"Potere, politica e pressioni istituzionali.",
  signals:["\"era giusta per il mondo di prima\"","il mercato è diventato imprevedibile","centralizzato vs decentrato","\"dipende da…\""],
  facts:["Burns & Stalker (1961) studiarono aziende scozzesi che entravano nell'elettronica. Le organizzazioni meccaniche (rigide, gerarchiche) faticavano a innovare, quelle organiche (fluide, a rete) si adattavano meglio.","Joan Woodward confrontò circa 100 aziende del South Essex e scoprì che la struttura efficace dipendeva dalla tecnologia produttiva: su commessa, di massa o a processo continuo.","Il nome contingency theory viene da Lawrence & Lorsch (1967)."],
  vx:"Negli anni '90, con il PC, il mercato cambiò rapidamente e IBM rischiò grosso. Oggi i mercati di cloud e AI si muovono velocemente: la struttura attuale crea fit?"},
 {id:"eco",code:"ECO",name:"Economica",era:"~1970–1990",people:"Coase · Williamson · Jensen & Meckling",
  q:"Perché esistono le organizzazioni, invece del solo mercato?",
  idea:"Costi di transazione: si sceglie tra comprare sul mercato o fare internamente, in base a quanto costa coordinare le transazioni. Teoria dell'agenzia: attori diversi hanno interessi diversi, per esempio azionisti e management, quindi servono incentivi, monitoraggio, governance e contratti.",
  why:"Se i mercati sono efficienti, perché esistono aziende enormi con gerarchie interne? Serviva spiegare i confini dell'organizzazione. Oggi ne restano outsourcing, decisioni make-or-buy, corporate governance e sistemi di incentivi.",
  sees:"Governance, incentivi o confini organizzativi che creano inefficienza.",
  rec:"Riprogettare incentivi, contratti, monitoraggio o scelte make-or-buy.",
  blind:"Cultura, significato, organizzazione informale.",
  signals:["make or buy, outsourcing","bonus e conflitti di interesse","\"il manager persegue i propri interessi\"","contratti difficili da scrivere"],
  facts:["Coase pubblicò The Nature of the Firm nel 1937, sviluppando idee nate da giovane durante un viaggio di studio negli Stati Uniti. Vinse il Nobel nel 1991.","Williamson vinse il Nobel nel 2009 insieme a Elinor Ostrom. La sua teoria usa la razionalità limitata di Simon: le lenti si parlano tra loro.","Il paper di Jensen & Meckling (1976) è tra i più citati nell'economia d'impresa e contribuì a diffondere i compensi dei manager legati al valore delle azioni."],
  vx:"IBM ha venduto il business dei PC a Lenovo (2005) e ha scorporato Kyndryl (2021). Perché ridefinire così i confini dell'azienda? E da quotata in borsa, come gestisce il problema di agenzia?"},
 {id:"ins",code:"INS",name:"Istituzionale",era:"~1970 →",people:"Meyer & Rowan · DiMaggio & Powell",
  q:"Perché le organizzazioni finiscono per assomigliarsi?",
  idea:"L'efficienza non spiega tutto: le organizzazioni adottano pratiche perché sono considerate legittime, professionali, attese. Le pressioni sono tre (isomorfismo): coercitiva (leggi e attori da cui dipendi), normativa (professioni ed esperti) e mimetica (copiare chi sembra avere successo).",
  why:"Molte organizzazioni adottavano strutture che non miglioravano le performance, e serviva spiegare perché. Oggi la lente spiega ESG, certificazioni, AI governance, sostenibilità e mode organizzative.",
  sees:"Pratiche adottate per legittimità più che per performance.",
  rec:"Esaminare le pressioni regolatorie, professionali e di imitazione.",
  blind:"Efficienza interna e motivazione individuale.",
  signals:["\"lo fanno tutti i concorrenti\"","investitori o società se lo aspettano","legge che impone → coercitiva","non migliora le performance ma si fa comunque"],
  facts:["Il paper di DiMaggio & Powell (1983) si intitola The Iron Cage Revisited, un omaggio diretto all'iron cage di Weber.","Meyer & Rowan (1977) descrivono le strutture formali come \"mito e cerimonia\". Spesso la struttura ufficiale è scollegata (decoupling) da come si lavora davvero.","L'imitazione cresce con l'incertezza: quando non sai cosa funziona, copi chi sembra avere successo."],
  vx:"Strategie AI, ESG, ethics board: quanto adotta IBM per efficienza e quanto per legittimità, anche verso i clienti enterprise che si aspettano queste pratiche?"},
];
const QUIZ = [
 {id:"q1",lens:"ins",s:"A Swiss insurer launches an \"AI strategy\" and publishes an ESG report. Management admits neither improves performance, but all competitors do it and investors expect it.",a:"Which lens explains this behaviour best?",o:[
  ["Institutional theory","Motivo: legittimità e imitazione, non efficienza. È isomorfismo mimetico, più le aspettative degli investitori.",1],
  ["Decision-making theory","C'è una decisione, ma nessun segnale di informazioni limitate o di satisficing. Che ci sia una decisione non basta per scegliere questa lente."],
  ["Classical theory","La classica spiega pratiche adottate per efficienza, ma qui l'azienda ammette che l'efficienza non migliora."],
  ["Human Relations","Nessun elemento su motivazione, gruppi o riconoscimento dei dipendenti."]]},
 {id:"q2",lens:"con",s:"A manufacturer with highly specialized departments and a strict hierarchy was successful for decades. Now the market is unpredictable and customers want customized products. A consultant says: \"Your structure wasn't wrong. It fit the old world.\"",a:"Which lens is the consultant using, and what would Burns & Stalker suggest?",o:[
  ["Contingency: move toward a more organic structure","\"Adatta al mondo di prima\" parla di fit con il contesto. Ambiente dinamico → struttura organica: reti, meno gerarchia, ruoli flessibili.",1],
  ["Contingency: move toward a more mechanistic structure","La lente è giusta, la direzione no: la struttura meccanica funziona negli ambienti stabili."],
  ["Classical: clarify roles and add controls","Più controllo in un ambiente instabile aumenta la rigidità. È il riflesso che il consulente mette in discussione."],
  ["Systems: the firm is a closed system","I sistemi sono aperti per definizione. E il consulente parla di adattamento al contesto, non di interdipendenze interne."]]},
 {id:"q3",lens:"dec",s:"At a logistics company every purchase above CHF 500 needs three approvals. Key data sits at headquarters, and regional managers often pick the first supplier that meets minimum criteria because they lack time to compare.",a:"Which lens gives the most direct diagnosis?",o:[
  ["Decision-making theory","Tre segnali di razionalità limitata: informazioni nel posto sbagliato, colli di bottiglia e satisficing.",1],
  ["Classical theory","Le approvazioni sono controllo, ma il problema descritto riguarda come circolano informazioni e decisioni."],
  ["Economic theory","Non c'è un conflitto di interessi né una scelta make-or-buy."],
  ["Contingency theory","Non si parla di un ambiente cambiato né di fit."]]},
 {id:"q4",lens:"sys",s:"A hospital introduces a new digital scheduling tool. Nurses who used to coordinate shifts informally must now follow the tool; handovers break down, overtime rises, and senior nurses feel their expertise no longer counts.",a:"Which lens best explains why the \"better\" technology made things worse?",o:[
  ["Sociotechnical systems theory","La tecnologia è cambiata senza riprogettare insieme persone, ruoli e coordinamento. È lo stesso schema delle miniere di Trist.",1],
  ["Human Relations","Coglie la frustrazione, ma non il meccanismo: il problema nasce dall'interazione tra tecnologia, persone e processi."],
  ["Classical theory","Al contrario: la classica direbbe che più standardizzazione è meglio."],
  ["Institutional theory","Nulla indica che lo strumento sia stato adottato per legittimità."]]},
 {id:"q5",lens:"eco",s:"A CEO's bonus depends on the quarterly share price. She cuts long-term R&D to boost short-term profit, against the interests of long-term shareholders.",a:"Which concept fits best?",o:[
  ["Agency theory","Gli interessi dell'agente (il CEO) divergono da quelli del principale (gli azionisti). La risposta tipica: ridisegnare incentivi e governance.",1],
  ["Transaction cost economics","Stessa famiglia teorica, ma riguarda il fare o comprare, non il conflitto tra principale e agente."],
  ["Bounded rationality","Non le mancano informazioni: la scelta è razionale rispetto ai suoi incentivi."],
  ["Mimetic isomorphism","Non sta copiando nessuno."]]},
 {id:"q6",lens:"eco",s:"A watch brand outsources cleaning and payroll but keeps movement design in-house, because that knowledge is highly specific and hard to protect in a contract.",a:"What explains where the company draws its boundary?",o:[
  ["Transaction cost economics","Le attività standard si comprano sul mercato; quelle specifiche e difficili da contrattualizzare si tengono in casa.",1],
  ["Contingency theory","Spiega la struttura interna rispetto all'ambiente, non cosa fare in casa e cosa comprare."],
  ["Agency theory","Stessa famiglia, ma qui il concetto chiave è il costo della transazione, non gli incentivi dei manager."],
  ["Classical specialization","La specializzazione divide il lavoro dentro l'azienda. Qui si decide dove finisce l'azienda."]]},
 {id:"q7",lens:"cls",s:"A call center times every call, gives agents word-for-word scripts, and has managers redesign the process while agents only execute.",a:"Which organizational logic is this?",o:[
  ["Classical / scientific management","Dividere, standardizzare, controllare, e chi pianifica è separato da chi esegue: è Taylor puro.",1],
  ["Human Relations","È l'opposto: nessuna attenzione a motivazione o gruppi."],
  ["Contingency theory","Non si discute di fit con l'ambiente."],
  ["Sociotechnical systems","Non ottimizza insieme persone e tecnologia: ottimizza solo il compito."]]},
 {id:"q8",lens:"hr",s:"A research team is moved into a highly visible pilot project. Pay stays the same, but managers ask for their opinions every week. Productivity rises, even in weeks when working conditions get slightly worse.",a:"What does this most resemble?",o:[
  ["The Hawthorne studies","Attenzione, partecipazione e dinamiche sociali contano più delle condizioni fisiche. È ciò che sorprese i ricercatori a Hawthorne.",1],
  ["Scientific management","Taylor cercherebbe il metodo ottimale; qui peggiorare le condizioni non abbassa la produttività."],
  ["Satisficing","Non c'è nessuna decisione presa con informazioni limitate."],
  ["Normative isomorphism","Non c'è nessuna pressione professionale esterna."]]},
 {id:"q9",lens:"hr",s:"A manager believes employees avoid work unless controlled. He adds time tracking and tight supervision. Over time, employees show less initiative, which \"confirms\" his view.",a:"Which idea explains this cycle?",o:[
  ["McGregor's Theory X as a self-fulfilling assumption","Theory X è un'assunzione del manager. L'assunzione diventa struttura (controllo), e la struttura produce il comportamento atteso. Collega con il Cap. 1!",1],
  ["Herzberg's hygiene factors","Herzberg distingue fattori igienici e motivanti. Qui il centro è la profezia che si autoavvera."],
  ["Agency theory","C'è monitoraggio, ma la causa del circolo è l'assunzione sulle persone, non un conflitto di interessi."],
  ["Weber's bureaucracy","Weber descrive regole formali e impersonali, non un circolo di aspettative."]]},
 {id:"q10",lens:"hr",s:"After a salary increase, complaints at a design studio drop, but designers are no more engaged. Engagement rises only when they get more responsibility for client projects.",a:"Which theory fits best?",o:[
  ["Herzberg's two-factor theory","Lo stipendio è un fattore igienico: toglie insoddisfazione. Responsabilità e riconoscimento sono i motivatori.",1],
  ["Maslow's hierarchy of needs","Ci si avvicina, ma la distinzione tra togliere insoddisfazione e creare motivazione è di Herzberg."],
  ["Scientific management","Taylor punterebbe proprio sulla paga come leva principale."],
  ["Contingency theory","L'ambiente esterno non c'entra."]]},
 {id:"q11",lens:"pol",s:"A company pays salaries, colleagues help each other without being asked, and part of the profit flows to a foundation that funds local projects.",a:"According to Polanyi, which statement is most accurate?",o:[
  ["Market exchange, reciprocity and redistribution coexist","Salario = mercato; aiuto spontaneo = reciprocità; fondazione che raccoglie e ridistribuisce = redistribuzione. Nella realtà le forme convivono.",1],
  ["It is pure market exchange, because it's a company","Trappola: un'azienda non vive solo di mercato."],
  ["Helping colleagues is redistribution","Nessun centro raccoglie e ridistribuisce: è reciprocità."],
  ["The foundation is reciprocity","Un centro che raccoglie e alloca risorse è redistribuzione."]]},
 {id:"q12",lens:"bel",s:"Mia is thirsty. She wants a specific Swiss mineral water and has the money for it, but she hasn't gone to a shop or expressed any intention to buy yet.",a:"At which stage is she?",o:[
  ["A want backed by purchasing power","Desiderio specifico più mezzi finanziari. La domanda nasce solo quando esprime l'intenzione di comprare.",1],
  ["Demand","Trappola: manca l'intenzione di acquisto espressa verso un fornitore."],
  ["Only a need","È più di un bisogno: il desiderio è specifico e può permetterselo."],
  ["Scarcity","La scarsità è un'assunzione economica, non una fase."]]},
 {id:"q13",lens:"bel",s:"A company's leadership fully accepts the assumption: \"Human needs are unlimited and resources are scarce.\"",a:"Which practice follows most directly from this assumption?",o:[
  ["Units compete for budgets and are measured by efficiency KPIs","Scarsità → competizione, ottimizzazione, misurazione delle performance, controllo dei costi.",1],
  ["Repair services and longer product lifecycles","Deriva dall'assunzione opposta: sufficienza e sostenibilità."],
  ["Shared ownership and cooperation between units","Viene da un'assunzione alternativa: la cooperazione può creare più valore della competizione."],
  ["Choosing the first acceptable option","È satisficing (Simon), non una conseguenza della scarsità."]]},
 {id:"q14",lens:"ins",s:"After a new federal law, all hospitals in a canton set up the same kind of patient-data compliance office.",a:"Which form of isomorphism is this?",o:[
  ["Coercive","La pressione viene da leggi e regolamenti.",1],
  ["Mimetic","Non copiano per incertezza: sono obbligati."],
  ["Normative","La spinta non viene da norme professionali."],
  ["None, it's contingency fit","La contingency non spiega perché tutti diventano uguali."]]},
 {id:"q15",lens:"ins",s:"Most design management graduates learn design thinking at university. When they become managers, their companies run design thinking workshops, whether or not they improve results.",a:"Which institutional pressure is most visible?",o:[
  ["Normative","Formazione e reti professionali diffondono \"il modo giusto\" di lavorare.",1],
  ["Coercive","Nessuna legge lo impone."],
  ["Mimetic","Può esserci in parte, ma qui la fonte è la formazione professionale."],
  ["It's Human Relations","Un workshop non è di per sé una spiegazione basata sulla motivazione."]]},
 {id:"q16",lens:"dec",s:"An insurer gives claims handlers clear rules for 90% of cases so they don't analyze every claim from scratch. Only unusual cases go to experts.",a:"Through the decision-making lens, why do such routines exist?",o:[
  ["They compensate for bounded rationality","Nessuno può analizzare tutto: regole e routine riducono il carico cognitivo. Per Simon sono un supporto alle decisioni.",1],
  ["To control workers, as Taylor would","La somiglianza è superficiale (ci sono regole), ma il motivo qui è cognitivo, non il controllo."],
  ["To gain legitimacy","Nessun segnale di aspettative esterne."],
  ["To reduce transaction costs with suppliers","Non ci sono transazioni di mercato."]]},
 {id:"q17",lens:"cls",s:"In class, each lens was tested on Alpine Manufacturing: falling productivity, silos, slow decisions, and management reacting with more rules and reporting.",a:"What is the typical blind spot of the classical lens?",o:[
  ["Motivation, informal relationships and adaptation","Guarda la macchina, non le persone né l'ambiente che cambia.",1],
  ["Efficiency and standardization","È proprio ciò che vede meglio."],
  ["Internal efficiency and individual motivation","Questo è il punto cieco della lente istituzionale."],
  ["Power, politics and institutional pressures","Questo è il punto cieco della contingency."]]},
 {id:"q18",lens:"cls",s:"At Toyota, any worker can pull a cord to stop the production line when they spot a quality problem.",a:"Which element goes beyond classical thinking?",o:[
  ["Workers act as problem-solvers, not only executors","La classica separa chi pensa da chi esegue. Toyota dà agli operai autorità e responsabilità sulla qualità.",1],
  ["Standardized work","Toyota standardizza molto: questa parte è ancora classica."],
  ["Hierarchical control","È il contrario di ciò che fa la corda."],
  ["Measuring cycle times","È ancora logica classica."]]},
 {id:"q19",lens:"eco",vx:true,s:"Training case inspired by IBM: a large listed tech company sells its PC business and later spins off its infrastructure-services unit, to concentrate on hybrid cloud and AI.",a:"Which lens most directly asks where the boundaries of the firm should be?",o:[
  ["Economic theory (transaction costs, make-or-buy)","La lente economica chiede cosa tenere dentro e cosa lasciare al mercato. Vendere o scorporare un'unità ridisegna i confini dell'azienda.",1],
  ["Human Relations","Conta per le persone coinvolte, ma non spiega la scelta dei confini."],
  ["Institutional theory","Può esserci una spinta di legittimità verso cloud e AI, ma la domanda sui confini è economica."],
  ["Classical theory","La classica organizza il lavoro dentro i confini, non decide dove metterli."]]},
 {id:"q20",lens:"pol",s:"A Swiss company keeps its apprenticeship programme and negotiates with unions, even though cheaper options exist abroad.",a:"Which Chapter 2 idea explains this best?",o:[
  ["Embeddedness","Le scelte economiche sono immerse in norme, istituzioni e cultura della società.",1],
  ["Market exchange","Il mercato da solo suggerirebbe l'opzione più economica."],
  ["Scarcity assumption","È del Cap. 1, e spingerebbe verso l'efficienza."],
  ["Satisficing","È del Cap. 3, lente decisionale."]]}
];
const PAIRS = [
 {id:"p1",s:"\"Non esiste un modo migliore: dipende dall'ambiente.\"",a:"con",b:"sys",why:"\"Dipende da\" è la firma della contingency. I sistemi parlano di interdipendenze, non di quale struttura scegliere."},
 {id:"p2",s:"\"Abbiamo cambiato software, e sono cambiati ruoli, competenze e collaborazione.\"",a:"sys",b:"con",why:"Effetti a catena tra tecnologia, persone e processi: prospettiva sociotecnica."},
 {id:"p3",s:"\"Riduciamo i costi standardizzando ogni movimento.\"",a:"cls",b:"eco",why:"Efficienza attraverso metodo e standard: Taylor. L'economica parlerebbe di transazioni e incentivi."},
 {id:"p4",s:"\"Lo produciamo internamente, perché un contratto con un fornitore sarebbe troppo rischioso.\"",a:"eco",b:"cls",why:"Make-or-buy e contratti difficili da scrivere: costi di transazione (Williamson)."},
 {id:"p5",s:"\"Le persone restano per il senso di appartenenza al gruppo.\"",a:"hr",b:"ins",why:"Appartenenza e relazioni informali spiegano il comportamento: Human Relations."},
 {id:"p6",s:"\"Introduciamo lo smart working perché ormai è ciò che ci si aspetta da un datore moderno.\"",a:"ins",b:"hr",why:"Il motivo è l'aspettativa esterna, cioè la legittimità, non la motivazione: istituzionale."},
 {id:"p7",s:"\"Il manager sceglie la prima soluzione che soddisfa i criteri minimi.\"",a:"dec",b:"cls",why:"È la definizione di satisficing (Simon)."},
 {id:"p8",s:"\"Il capo reparto pianifica, gli operai eseguono.\"",a:"cls",b:"dec",why:"La separazione tra pianificare ed eseguire è un pilastro della lente classica."},
 {id:"p9",s:"\"Gli azionisti temono che il CEO persegua i propri interessi.\"",a:"eco",b:"dec",why:"Conflitto tra principale e agente: teoria dell'agenzia."},
 {id:"p10",s:"\"Nessuno ha tutte le informazioni, quindi creiamo routine.\"",a:"dec",b:"eco",why:"Routine come risposta alla razionalità limitata: lente decisionale."},
 {id:"p11",s:"\"Prendiamo risorse e informazioni dall'ambiente e le restituiamo trasformate.\"",a:"sys",b:"con",why:"Input → trasformazione → output: è la definizione di sistema aperto."},
 {id:"p12",s:"\"Siamo piccoli e il mercato è stabile: restare centralizzati per noi funziona.\"",a:"con",b:"sys",why:"Dimensione e ambiente determinano la struttura adatta: fit, quindi contingency."},
 {id:"p13",s:"\"Pago le tasse e lo Stato finanzia l'università pubblica.\"",a:"pol",b:"bel",why:"Un centro raccoglie e ridistribuisce: redistribuzione (Polanyi, Cap. 2)."},
 {id:"p14",s:"\"Se crediamo che le risorse siano scarse, è ovvio che i reparti competano.\"",a:"bel",b:"pol",why:"Un'assunzione che genera valori e pratiche: catena del Cap. 1."},
 {id:"p15",s:"\"Aumentare lo stipendio ha fermato le lamentele, ma non ha motivato nessuno.\"",a:"hr",b:"eco",why:"Fattori igienici contro motivatori: Herzberg. L'economica vedrebbe solo l'incentivo."},
 {id:"p16",s:"\"Tutti gli ospedali hanno lo stesso ufficio compliance perché la legge lo impone.\"",a:"ins",b:"cls",why:"Isomorfismo coercitivo: le organizzazioni diventano simili per pressione normativa esterna."}
];
const PEOPLE = {
 taylor:{name:"Frederick W. Taylor",dates:"1856–1915",lens:"cls",role:"Ingegnere meccanico statunitense, padre dello Scientific Management",
  world:"Acciaierie americane di fine Ottocento (Midvale Steel, Bethlehem Steel). Il lavoro si faceva \"a occhio\", seguendo regole empiriche, e gli operai rallentavano di proposito (soldiering) per paura di essere pagati meno.",
  said:"Ogni compito si può studiare scientificamente, con tempi e movimenti, per trovare la one best way. Il management seleziona, addestra e pianifica; l'operaio esegue il metodo prescritto e viene pagato con incentivi a cottimo.",
  today:"Lean, KPI, time tracking e il cosiddetto algorithmic management (pensa alle app di consegne che misurano ogni minuto) sono eredi diretti di Taylor.",
  work:"The Principles of Scientific Management (1911)",
  fact:"Il suo sistema era così controverso che, dopo uno sciopero all'arsenale di Watertown nel 1911, una commissione speciale del Congresso USA lo sottopose a un'indagine con audizioni.",
  confuse:"Fayol: Taylor guarda l'azienda dal basso (il compito in officina), Fayol dall'alto (il lavoro del direttore).",
  wiki:"Frederick_Winslow_Taylor"},
 fayol:{name:"Henri Fayol",dates:"1841–1925",lens:"cls",role:"Ingegnere minerario francese, direttore d'azienda, padre dell'Administrative Management",
  world:"Fu per decenni direttore generale di un gruppo minerario e metallurgico francese (Commentry-Fourchambault), che risollevò da una situazione difficile.",
  said:"Il management è un'attività universale che si può insegnare. Ha cinque funzioni: prevedere, organizzare, comandare, coordinare, controllare. Propose anche 14 principi, tra cui divisione del lavoro, unità di comando, scala gerarchica ed esprit de corps.",
  today:"Organigrammi, catena di comando e le \"funzioni del management\" dei manuali vengono in gran parte da lui.",
  work:"Administration industrielle et générale (1916)",
  fact:"Per Fayol ogni dipendente dovrebbe avere un solo capo (unità di comando). Le strutture a matrice, come quella di IBM, violano apertamente questo principio: interessante da discutere nel progetto.",
  confuse:"Taylor: Fayol non cronometra i compiti, descrive cosa deve fare chi dirige.",
  wiki:"Henri_Fayol"},
 weber:{name:"Max Weber",dates:"1864–1920",lens:"cls",role:"Sociologo, economista e giurista tedesco, teorico della burocrazia",
  world:"La Germania che si industrializza e costruisce uno Stato moderno. Weber si chiede su cosa si fondi un'autorità legittima e come la società diventi \"razionale\".",
  said:"L'autorità può essere tradizionale, carismatica o legale-razionale. La burocrazia (gerarchia, regole scritte, impersonalità, funzionari scelti per competenza) sostituisce favoritismo e arbitrio con regole uguali per tutti.",
  today:"Procedure, compliance, selezione basata su criteri e documentazione scritta. Ma anche la critica alla \"burocrazia\" che rallenta.",
  work:"Economia e società (postumo, 1922); L'etica protestante e lo spirito del capitalismo (1904–05)",
  fact:"Temeva che la razionalità diventasse un guscio \"duro come l'acciaio\", tradotto in inglese come iron cage. Nel 1983 DiMaggio & Powell intitolano il loro paper The Iron Cage Revisited.",
  confuse:"Taylor e Fayol: Weber non guarda il compito né il manager, ma l'organizzazione intera e la legittimità dell'autorità.",
  wiki:"Max_Weber"},
 mayo:{name:"Elton Mayo",dates:"1880–1949",lens:"hr",role:"Psicologo e sociologo industriale australiano, Harvard Business School",
  world:"Anni '20 e '30: fabbriche tayloriste, conflitti tra operai e direzione. Si pensava che luce, pause e paga spiegassero la produttività.",
  said:"I lavoratori sono esseri sociali. Gruppi informali, bisogno di appartenenza, attenzione e riconoscimento influenzano la performance più delle condizioni fisiche. È diventato il volto degli studi di Hawthorne.",
  today:"Team culture, engagement, attenzione ai gruppi informali e alla leadership.",
  work:"The Human Problems of an Industrial Civilization (1933)",
  fact:"Gli studi di Hawthorne (Western Electric, vicino a Chicago) iniziarono prima del suo arrivo. Oggi i loro dati sono molto discussi e l'\"effetto Hawthorne\" è contestato da diverse rianalisi.",
  confuse:"Maslow: Mayo parte da osservazioni in fabbrica sui gruppi, Maslow da una teoria psicologica dei bisogni individuali.",
  wiki:"Elton_Mayo"},
 maslow:{name:"Abraham Maslow",dates:"1908–1970",lens:"hr",role:"Psicologo statunitense, fondatore della psicologia umanistica",
  world:"La psicologia di metà Novecento studiava soprattutto patologie e comportamenti. Maslow voleva capire cosa spinge le persone a crescere.",
  said:"I bisogni formano una gerarchia: fisiologici, sicurezza, appartenenza, stima, autorealizzazione. I bisogni più alti diventano motivanti quando quelli più bassi sono in gran parte soddisfatti.",
  today:"Discorsi su purpose, crescita personale e benessere al lavoro. Molto usato, ma anche criticato per scarse prove empiriche.",
  work:"A Theory of Human Motivation (1943); Motivation and Personality (1954)",
  fact:"La famosa piramide non è di Maslow: la forma grafica fu diffusa da altri autori dopo di lui.",
  confuse:"Herzberg: Maslow ha una scala di bisogni; Herzberg divide i fattori in due gruppi separati (igienici e motivanti).",
  wiki:"Abraham_Maslow"},
 herzberg:{name:"Frederick Herzberg",dates:"1923–2000",lens:"hr",role:"Psicologo statunitense, teoria dei due fattori",
  world:"Fine anni '50: le aziende cercavano di motivare con stipendi e condizioni migliori, con risultati deludenti.",
  said:"Soddisfazione e insoddisfazione non sono gli estremi di una sola scala. I fattori igienici (stipendio, condizioni, regole, supervisione) evitano l'insoddisfazione; i motivatori (risultati, riconoscimento, responsabilità, lavoro in sé, crescita) creano motivazione.",
  today:"Job enrichment: dare più responsabilità e autonomia invece di aumentare solo la paga.",
  work:"The Motivation to Work (1959); \"One More Time: How Do You Motivate Employees?\" (Harvard Business Review, 1968)",
  fact:"La teoria nacque da interviste a circa 200 ingegneri e contabili di Pittsburgh, a cui chiese di raccontare momenti in cui si erano sentiti particolarmente bene o male al lavoro.",
  confuse:"Maslow: per Herzberg il contrario di \"soddisfatto\" non è \"insoddisfatto\", ma \"non soddisfatto\".",
  wiki:"Frederick_Herzberg"},
 mcgregor:{name:"Douglas McGregor",dates:"1906–1964",lens:"hr",role:"Professore di management al MIT",
  world:"Anni '50: management ancora molto basato su comando e controllo, mentre la psicologia mostrava un'immagine più ricca delle persone.",
  said:"I manager agiscono in base ad assunzioni sulle persone. Theory X: le persone evitano il lavoro e vanno controllate. Theory Y: le persone cercano responsabilità se il contesto lo permette. Le assunzioni tendono ad autoavverarsi.",
  today:"Fiducia, autonomia e lavoro ibrido: ogni discussione su \"controllare o fidarsi\" è X contro Y.",
  work:"The Human Side of Enterprise (1960)",
  fact:"Prima di tornare al MIT fu presidente dell'Antioch College, un'esperienza che mise alla prova le sue idee sulla leadership.",
  confuse:"Non sono due tipi di lavoratori, ma due visioni dei manager. Collegamento diretto con il Cap. 1: le assunzioni diventano strutture.",
  wiki:"Douglas_McGregor"},
 simon:{name:"Herbert A. Simon",dates:"1916–2001",lens:"dec",role:"Economista, politologo, psicologo cognitivo e informatico statunitense",
  world:"L'economia classica assumeva un decisore perfettamente razionale. Simon studiava le amministrazioni reali e vedeva tutt'altro.",
  said:"Razionalità limitata: informazioni, tempo e capacità cognitive sono limitati. Si sceglie la prima opzione abbastanza buona (satisficing), e le organizzazioni creano routine e regole per aiutare le decisioni.",
  today:"Diritti decisionali, sistemi informativi, supporto AI alle decisioni: progettare un'organizzazione è progettare decisioni.",
  work:"Administrative Behavior (1947); Organizations (1958, con March)",
  fact:"Vinse il Nobel per l'economia (1978) e il Turing Award (1975). Con Allen Newell creò nel 1956 il Logic Theorist, uno dei primi programmi di intelligenza artificiale.",
  confuse:"Williamson usa la razionalità limitata di Simon, ma per spiegare i confini dell'impresa: la lente è economica.",
  wiki:"Herbert_A._Simon"},
 march:{name:"James G. March",dates:"1928–2018",lens:"dec",role:"Studioso di organizzazioni e decisioni, Stanford",
  world:"Dopo Simon: se la razionalità è limitata, come decidono e imparano davvero le organizzazioni?",
  said:"Le organizzazioni sono coalizioni con obiettivi diversi, che decidono tramite routine e regole. Nel garbage can model (1972, con Cohen e Olsen) problemi, soluzioni e decisori si incontrano quasi per caso.",
  today:"Innovazione e apprendimento organizzativo: il dilemma tra sfruttare ciò che sai e esplorare il nuovo.",
  work:"Organizations (1958, con Simon); A Behavioral Theory of the Firm (1963, con Cyert)",
  fact:"Il suo articolo del 1991 su exploration ed exploitation è la base del concetto di ambidexterity, che vedrai nel Cap. 6. Pubblicava anche raccolte di poesie.",
  confuse:"Simon: March sposta l'attenzione dal singolo decisore ai processi collettivi e all'apprendimento.",
  wiki:"James_G._March"},
 bertalanffy:{name:"Ludwig von Bertalanffy",dates:"1901–1972",lens:"sys",role:"Biologo austriaco, fondatore della teoria generale dei sistemi",
  world:"La biologia del primo Novecento: un organismo non si capisce smontandolo pezzo per pezzo, perché vive di scambi continui con l'ambiente.",
  said:"Esistono principi comuni a tutti i sistemi: biologici, sociali, tecnici. I sistemi aperti scambiano energia e informazione con l'ambiente, e lo stesso risultato si può raggiungere per strade diverse (equifinalità).",
  today:"Systems thinking, ecosistemi, digital transformation vista come cambiamento dell'intero sistema.",
  work:"General System Theory (1968)",
  fact:"Era un biologo, non un teorico del management: le organizzazioni come \"organismi\" vengono dalle sue idee.",
  confuse:"Katz & Kahn: Bertalanffy crea la teoria generale, loro la applicano esplicitamente alle organizzazioni.",
  wiki:"Ludwig_von_Bertalanffy"},
 katzkahn:{name:"Daniel Katz & Robert L. Kahn",dates:"1903–1998 · 1918–2019",lens:"sys",role:"Psicologi sociali statunitensi, University of Michigan",
  world:"Anni '60: gli studi organizzativi guardavano quasi solo dentro l'azienda, come se fosse un sistema chiuso.",
  said:"L'organizzazione è un sistema aperto: input dall'ambiente, trasformazione (throughput), output restituito. Sopravvive solo se questo ciclo si rinnova.",
  today:"Pensare per catene del valore, flussi end-to-end e dipendenze da clienti, fornitori e partner.",
  work:"The Social Psychology of Organizations (1966)",
  fact:"Robert Kahn visse oltre 100 anni: nato nel 1918, morto nel 2019.",
  confuse:"Contingency: entrambi guardano l'ambiente, ma i sistemi spiegano le interdipendenze, la contingency quale struttura scegliere.",
  wiki:"Open_system_(systems_theory)"},
 tristemery:{name:"Eric Trist & Fred Emery",dates:"1909–1993 · 1925–1997",lens:"sys",role:"Ricercatori del Tavistock Institute di Londra, teoria sociotecnica",
  world:"Il dopoguerra britannico: nuove tecnologie nelle miniere e nelle fabbriche promettevano produttività, ma spesso peggioravano le cose.",
  said:"Sistema sociale e sistema tecnico vanno progettati insieme (joint optimization). Ottimizzare solo la tecnologia peggiora il sistema intero.",
  today:"Ogni introduzione di software, automazione o AI che fallisce perché nessuno ha ripensato ruoli e collaborazione.",
  work:"Trist & Bamforth (1951) sulle miniere di carbone; Emery & Trist, \"The Causal Texture of Organizational Environments\" (1965)",
  fact:"Nel 1965 descrissero gli ambienti \"turbolenti\", in cui tutto cambia insieme: un'idea che anticipa il Cap. 6 sulla complessità.",
  confuse:"Human Relations: i sociotecnici non guardano solo le persone, ma l'incastro tra persone e tecnologia.",
  wiki:"Sociotechnical_system"},
 woodward:{name:"Joan Woodward",dates:"1916–1971",lens:"con",role:"Sociologa industriale britannica",
  world:"Anni '50: si credeva ancora nei principi universali di Fayol. Woodward volle verificarli con i dati.",
  said:"Studiando circa 100 aziende del South Essex scoprì che nessun principio universale prediceva il successo. Le aziende di successo avevano una struttura adatta alla loro tecnologia: produzione su commessa, di massa o a processo continuo.",
  today:"L'idea che la tecnologia (oggi digitale e AI) cambi la struttura organizzativa più adatta.",
  work:"Industrial Organization: Theory and Practice (1965)",
  fact:"Partì cercando di confermare i principi classici e finì per smontarli: un ottimo esempio di distinzione tra assunzione ed evidenza.",
  confuse:"Burns & Stalker: Woodward lega la struttura alla tecnologia, Burns & Stalker all'ambiente di mercato.",
  wiki:"Joan_Woodward"},
 burnsstalker:{name:"Tom Burns & G. M. Stalker",dates:"Burns 1913–2001",lens:"con",role:"Sociologo e psicologo, ricerca in Scozia",
  world:"Dopo la guerra aziende scozzesi tradizionali provarono a entrare nell'elettronica, un settore nuovo e in rapidissimo cambiamento.",
  said:"Le organizzazioni meccaniche (ruoli rigidi, gerarchia, comunicazione verticale) funzionano in ambienti stabili. Quelle organiche (ruoli fluidi, reti, comunicazione laterale) funzionano in ambienti incerti e innovativi.",
  today:"Il dibattito agile contro gerarchico e le unità di innovazione separate nelle grandi aziende.",
  work:"The Management of Innovation (1961)",
  fact:"\"Organico\" non significa \"migliore\": in un ambiente stabile la struttura meccanica è la scelta giusta. È una trappola frequente all'esame.",
  confuse:"Lawrence & Lorsch: Burns & Stalker confrontano aziende intere; Lawrence & Lorsch mostrano che reparti diversi della stessa azienda hanno bisogno di strutture diverse.",
  wiki:"Mechanistic_and_organic_systems"},
 lawrencelorsch:{name:"Paul Lawrence & Jay Lorsch",dates:"1922–2011 · 1932–",lens:"con",role:"Professori di Harvard Business School",
  world:"Anni '60: grandi aziende con reparti molto diversi (R&D, produzione, vendite) che faticavano a collaborare.",
  said:"Più l'ambiente è incerto, più i reparti si differenziano (obiettivi, tempi, stili). Quindi servono meccanismi di integrazione più forti per tenerli insieme: differentiation e integration.",
  today:"Silos, ruoli di coordinamento, team cross-funzionali, product manager come integratori.",
  work:"Organization and Environment (1967)",
  fact:"Sono loro ad aver coniato il termine contingency theory. Studiarono tre settori con incertezza diversa: plastica, alimentare e contenitori.",
  confuse:"Burns & Stalker: qui il focus è l'equilibrio tra differenziazione e integrazione dentro l'azienda.",
  wiki:"Contingency_theory"},
 mintzberg:{name:"Henry Mintzberg",dates:"1939–",lens:"con",role:"Studioso di management canadese, McGill University",
  world:"Anni '70: i manuali descrivevano il manager come un pianificatore razionale. Mintzberg andò a osservare cosa facevano davvero i dirigenti.",
  said:"Le organizzazioni si raggruppano in configurazioni coerenti: struttura semplice, burocrazia meccanica, burocrazia professionale, forma divisionale, adhocrazia. Ognuna funziona in un contesto diverso.",
  today:"Descrivere la struttura di un'azienda reale, per esempio le divisioni di IBM o una consulenza come adhocrazia.",
  work:"The Structuring of Organizations (1979); The Nature of Managerial Work (1973)",
  fact:"Osservando i CEO scoprì che il loro lavoro è frammentato: tante attività brevi, interruzioni continue, poco tempo per la riflessione. È anche un critico famoso degli MBA (Managers Not MBAs, 2004).",
  confuse:"Fayol: Fayol descrive come il manager dovrebbe lavorare, Mintzberg come lavora davvero.",
  wiki:"Henry_Mintzberg"},
 coase:{name:"Ronald Coase",dates:"1910–2013",lens:"eco",role:"Economista britannico, University of Chicago",
  world:"Anni '30: l'economia spiegava bene i mercati, ma non perché esistessero aziende con gerarchie interne.",
  said:"Coordinare tramite il mercato ha dei costi. Quando conviene, l'autorità interna sostituisce il prezzo: l'impresa esiste per questo, e i suoi confini dipendono da questi costi.",
  today:"Ogni decisione make-or-buy e ogni discussione su outsourcing.",
  work:"\"The Nature of the Firm\" (1937)",
  fact:"Vinse il Nobel nel 1991, oltre 50 anni dopo il suo articolo più famoso, e visse fino a 102 anni.",
  confuse:"Williamson: Coase pone la domanda, Williamson sviluppa in modo sistematico la teoria dei costi di transazione.",
  wiki:"Ronald_Coase"},
 williamson:{name:"Oliver E. Williamson",dates:"1932–2020",lens:"eco",role:"Economista statunitense, UC Berkeley",
  world:"Anni '70: grandi conglomerati, integrazione verticale e dibattito sul perché le aziende facciano internamente certe attività.",
  said:"Transaction Cost Economics: la scelta tra mercato e gerarchia dipende dalla specificità degli asset, dall'incertezza e dalla frequenza. Parte da due ipotesi: razionalità limitata e opportunismo.",
  today:"Outsourcing, partnership strategiche, piattaforme, integrazione verticale.",
  work:"Markets and Hierarchies (1975); The Economic Institutions of Capitalism (1985)",
  fact:"Si formò alla Carnegie, dove insegnava Simon, e vinse il Nobel 2009 insieme a Elinor Ostrom.",
  confuse:"Jensen & Meckling: Williamson spiega i confini dell'impresa, loro il conflitto tra proprietari e manager.",
  wiki:"Oliver_E._Williamson"},
 jensenmeckling:{name:"Michael C. Jensen & William H. Meckling",dates:"1939–2024 · 1921–1998",lens:"eco",role:"Economisti finanziari statunitensi",
  world:"Anni '70: grandi aziende quotate gestite da manager che non ne sono proprietari.",
  said:"Teoria dell'agenzia: il principale (gli azionisti) delega all'agente (il management), che può avere interessi diversi. Ne nascono costi di agenzia: monitoraggio, garanzie e perdite residue. Servono incentivi e governance.",
  today:"Stock option, bonus legati alle performance, consigli di amministrazione indipendenti, shareholder value.",
  work:"\"Theory of the Firm: Managerial Behavior, Agency Costs and Ownership Structure\" (1976)",
  fact:"È uno degli articoli più citati in economia e finanza. Il suo successo contribuì a diffondere compensi legati al prezzo delle azioni, con effetti poi molto discussi.",
  confuse:"Coase e Williamson: stessa lente economica, ma qui il tema è incentivi e conflitto di interessi, non make-or-buy.",
  wiki:"Principal–agent_problem"},
 meyerrowan:{name:"John W. Meyer & Brian Rowan",dates:"Meyer 1935–",lens:"ins",role:"Sociologi statunitensi, neo-istituzionalismo",
  world:"Anni '70: scuole e amministrazioni adottavano strutture formali che nella pratica quotidiana nessuno seguiva.",
  said:"Le strutture formali spesso sono \"mito e cerimonia\": servono a mostrare legittimità all'esterno. Per questo possono essere scollegate (decoupling) da come si lavora davvero.",
  today:"Codici etici, certificazioni o strategie che esistono sulla carta ma cambiano poco nella pratica.",
  work:"\"Institutionalized Organizations: Formal Structure as Myth and Ceremony\" (1977)",
  fact:"Decoupling è un'ottima parola per il progetto: la differenza tra ciò che un'azienda comunica e ciò che scopri nella Q&A.",
  confuse:"DiMaggio & Powell: Meyer & Rowan spiegano perché si adottano strutture per legittimità, loro perché le organizzazioni diventano simili.",
  wiki:"Institutional_theory"},
 dimaggiopowell:{name:"Paul DiMaggio & Walter W. Powell",dates:"entrambi 1951–",lens:"ins",role:"Sociologi statunitensi",
  world:"Anni '80: organizzazioni dello stesso settore sempre più simili, anche quando non ne ricavavano vantaggi di efficienza.",
  said:"Isomorfismo istituzionale, con tre meccanismi: coercitivo (leggi e attori da cui dipendi), mimetico (imitazione in condizioni di incertezza), normativo (professioni, formazione, reti di esperti).",
  today:"ESG, AI strategy, metodi agili, certificazioni: tutti i \"lo fanno tutti\".",
  work:"\"The Iron Cage Revisited: Institutional Isomorphism and Collective Rationality in Organizational Fields\" (1983)",
  fact:"Il titolo riprende l'iron cage di Weber: la gabbia oggi non viene più dall'efficienza, ma dalla pressione a somigliarsi.",
  confuse:"Human Relations: la norma normativa riguarda le professioni, non la motivazione dei dipendenti.",
  wiki:"Institutional_isomorphism"},
 polanyi:{name:"Karl Polanyi",dates:"1886–1964",lens:"pol",role:"Economista, storico e antropologo economico, nato a Vienna e di origine ungherese",
  world:"Visse la crisi del 1929, l'ascesa dei fascismi e la guerra. Voleva capire come la fiducia in un mercato autoregolato avesse destabilizzato le società.",
  said:"L'economia è embedded nella società. Nella storia l'integrazione economica avviene tramite reciprocità, redistribuzione e scambio di mercato. Il mercato che domina tutto è un'eccezione storica, non la norma.",
  today:"Discussioni su sostenibilità, welfare, economia sociale e sul ruolo delle imprese nella società.",
  work:"The Great Transformation (1944)",
  fact:"Suo fratello Michael Polanyi, chimico e filosofo, introdusse il concetto di tacit knowledge (conoscenza tacita), centrale nell'apprendimento organizzativo del Cap. 7.",
  confuse:"Istituzionale: Polanyi parla della società che contiene l'economia, i neo-istituzionalisti di pressioni specifiche su organizzazioni di uno stesso campo.",
  wiki:"Karl_Polanyi"}
};
const LESSON = [
 {id:"s1",part:"Kick-off",slides:"9–12",title:"Cosa si aspetta Joël, e la regola sull'AI",
  brief:"Le aspettative sono: partecipazione attiva, pensiero critico, collaborazione, ricerca autonoma, apprendimento pratico, feedback costruttivo, presenza costante. Sull'AI la regola è una sola: deve sostenere il tuo pensiero, non sostituirlo.",
  hook:"Per il progetto vale doppio: un fatto su IBM inventato o non verificato dall'AI non conta come evidenza.",
  ex:"Sì: farti spiegare Williamson, generare domande, proporre lenti possibili, strutturare idee, migliorare il linguaggio. No: generare la diagnosi finale, inventare fatti su IBM, sostituire la ricerca delle fonti, delegare l'interpretazione della teoria.",
  q:"Puoi chiedere all'AI di riassumere un report di IBM che non hai letto e citare il riassunto come fonte?",
  a:"No. L'AI può riassumere solo materiale che hai già verificato, e il riassunto non è evidenza: la fonte resta il report."},
 {id:"s2",part:"Kick-off",slides:"13",title:"La mappa del corso: 7 capitoli, 3 fasi",
  brief:"Foundations & Context (Cap. 1–3: credenze, economia, teorie). Organizational Basics (Cap. 4–5: scopo, stakeholder, struttura, processi). Systems & Adaptation (Cap. 6–7: complessità, persone, cultura, apprendimento).",
  hook:"Il corso va dal perché esistono le organizzazioni, al come funzionano, a come sopravvivono in un mondo che cambia.",
  ex:"Per IBM: i Cap. 1–3 ti danno le lenti, i Cap. 4–5 cosa osservare (scopo, ruoli, decision rights), i Cap. 6–7 le tensioni più interessanti da discutere.",
  q:"In quale capitolo rientrano \"decision rights\" e \"handovers\"?",
  a:"Nel Cap. 5, Work, Structures & Processes: tasks, roles and decision rights; processes, coordination and handovers."},
 {id:"s3",part:"Kick-off",slides:"15–18",title:"La missione: diagnosticare, con informazioni incomplete",
  brief:"Siete nel dipartimento di Organizational Design e il Head of Strategy vi chiede una diagnosi indipendente: come funziona oggi l'organizzazione, perché potrebbe essere organizzata così, dove potrebbe migliorare. I passi sono quattro: Prepare (desk research), Investigate (Q&A), Interpret (pattern e tensioni), Diagnose & Recommend.",
  hook:"L'evidenza ha quattro etichette: FACT (fonte pubblica), FINDING (dalla Q&A), INTERPRETATION (conclusione tramite teoria), ASSUMPTION (ciò che credi, con informazioni incomplete).",
  ex:"Esempio costruito, da non usare così com'è. FACT: IBM ha acquisito Red Hat nel 2019. FINDING: \"Red Hat mantiene processi propri\" (ipotetica risposta alla Q&A). INTERPRETATION: con la lente sociotecnica, integrare poco evita di rompere un sistema che funziona. ASSUMPTION: probabilmente esistono tensioni culturali tra i due mondi.",
  q:"\"IBM è lenta perché è grande\": che tipo di affermazione è?",
  a:"Un'ASSUMPTION. Per diventare diagnosi servono fatti (es. tempi decisionali), un finding dalla Q&A e una lente che spieghi il meccanismo (es. decisionale o contingency)."},
 {id:"s4",part:"Kick-off",slides:"20–23",title:"Cosa deve contenere il progetto",
  brief:"Requisiti minimi: Purpose & Context; Structure & Processes; almeno tre lenti teoriche; People, Culture & Learning; Fit & Trade-offs; una o due raccomandazioni realistiche con benefici e rischi. Presentazione di 15 minuti con una storia coerente, depth over breadth.",
  hook:"Il messaggio chiave: il vostro compito è diagnosticare, non descrivere. Una buona analisi non finge di sapere tutto, rende visibile l'incertezza.",
  ex:"Domanda sprecata alla Q&A: \"Quanti dipendenti ha IBM?\" (si trova online). Domanda utile: \"Quando un progetto coinvolge sia cloud sia consulting, chi ha l'ultima parola?\"",
  q:"Perché aprire la presentazione con la storia di IBM dal 1911 è una cattiva idea?",
  a:"È descrizione. La storia serve solo se spiega un pattern di oggi; in 15 minuti conta una diagnosi coerente."},
 {id:"s5",part:"Kick-off",slides:"26–27",title:"Come funziona l'esame",
  brief:"Valuta concetti chiave, prospettive teoriche, la capacità di riconoscere concetti nelle situazioni, implicazioni e trade-off. Formato: multiple choice, single choice, scenari, short case.",
  hook:"Il consiglio della slide: non memorizzare solo definizioni; chiediti cosa spiega ogni concetto, collegalo a situazioni reali, conosci benefici, limiti e trade-off.",
  ex:"È esattamente il motivo per cui questa pagina ha Detective e Coppie: allenano il riconoscere, non il ripetere.",
  q:"Qual è la domanda che riassume l'esame?",
  a:"Sai capire e applicare la teoria organizzativa da solo?"},
 {id:"s6",part:"Cap. 1",slides:"30",title:"Cos'è un'organizzazione?",
  brief:"Prima di ogni teoria il docente chiede la tua idea: disegnala, scrivila, fai domande, costruisci una mappa.",
  hook:"Ogni teoria del Cap. 3 risponderà in modo diverso a questa stessa domanda. Torna qui alla fine del percorso.",
  ex:"Prova a scrivere una frase adesso, prima di continuare.",
  q:"Come risponderebbero tre lenti diverse?",
  a:"Classica: una macchina progettata per l'efficienza. Human Relations: una rete di persone e relazioni. Economica: un'alternativa al mercato per coordinare transazioni. Nessuna è sbagliata, ognuna vede qualcosa."},
 {id:"s7",part:"Cap. 1",slides:"32",title:"Bisogno → want → domanda",
  brief:"Un bisogno nasce da una carenza percepita. Quando diventa un desiderio specifico che puoi permetterti, è un want backed by purchasing power. Diventa domanda solo quando esprimi l'intenzione di comprare da un fornitore.",
  hook:"Sembra banale, ma è una catena precisa, ed è una trappola perfetta per una domanda a scelta multipla.",
  ex:"Un'azienda sente la carenza di dati ordinati (bisogno). Vuole una specifica soluzione cloud e ha il budget (want backed by purchasing power). Chiede un'offerta a IBM (domanda).",
  q:"Hai sete, vuoi un Rivella e hai 3 franchi in tasca. È domanda?",
  a:"Non ancora: è un want backed by purchasing power. Diventa domanda quando esprimi l'intenzione di comprarlo, per esempio al bancone."},
 {id:"s8",part:"Cap. 1",slides:"33–34",title:"La scarsità e le assunzioni che porta con sé",
  brief:"Scarsità: le risorse sono finite, quindi si può produrre solo una quantità limitata di beni. È considerata il punto di partenza dell'economia, e porta con sé assunzioni: i bisogni sono illimitati, la scarsità va superata con divisione del lavoro e scambio, si compete per beni scarsi, il mercato è la forma migliore, i migliori prevalgono.",
  hook:"Attenzione alla parola \"assunzioni\": il docente non dice che sono vere o false, ma che sono credenze con conseguenze.",
  ex:"\"Le risorse sono finite\" è vicino a un fatto. \"Il mercato è la miglior forma di organizzazione\" è un'assunzione di valore.",
  q:"Perché distinguere tra fatto e assunzione conta anche nel progetto?",
  a:"È la stessa abilità richiesta con FACT e ASSUMPTION: il voto premia chi distingue ciò che sa da ciò che crede."},
 {id:"s9",part:"Cap. 1",slides:"35–37",title:"Cosa segue da ciò che crediamo",
  brief:"Le conseguenze della scarsità ai tre livelli. Individuale: competizione, accumulo, confronto, ottimizzazione. Organizzativo: obiettivi di efficienza, specializzazione, misurazione delle performance, competizione tra unità, controllo dei costi. Economico: mercati, prezzi come meccanismo di allocazione, orientamento alla crescita.",
  hook:"La frase da portarsi a casa: le assunzioni influenzano i valori, i valori le decisioni, e le decisioni ripetute costruiscono le organizzazioni.",
  ex:"KPI, budget in competizione e controllo dei costi in una grande azienda non sono \"naturali\": sono la scarsità trasformata in struttura.",
  q:"Chi beneficia della logica della scarsità, e che problemi può creare?",
  a:"Ne beneficia chi è già forte nella competizione. Problemi possibili: disuguaglianza, consumo eccessivo di risorse, competizione interna che distrugge la collaborazione. Non esiste una sola risposta: conta il ragionamento."},
 {id:"s10",part:"Cap. 1",slides:"38–41",title:"Rovescia l'assunzione",
  brief:"Scegli un'assunzione alternativa e completa la catena: assunzione → valori → comportamento → pratiche organizzative → sistema di coordinamento. Esempio: \"il benessere non richiede consumo illimitato\" → sufficienza e sostenibilità → condividere e riparare → economia circolare, riparazioni, proprietà condivisa → mercato + cooperazione + redistribuzione.",
  hook:"Assunzioni diverse producono realtà organizzative diverse. Davanti a ogni problema, chiediti cosa stiamo assumendo su persone, bisogni, competizione, valore, successo, crescita.",
  ex:"Nel progetto funziona benissimo: quale assunzione su crescita e innovazione sta dietro le scelte di IBM?",
  q:"Completa la catena per \"la cooperazione può creare più valore della competizione\".",
  a:"Valori: fiducia, condivisione. Comportamenti: aiutarsi, scambiare conoscenza. Pratiche: obiettivi e bonus di team, partnership, comunità di pratica. Coordinamento: più reciprocità accanto al mercato."},
 {id:"s11",part:"Cap. 2",slides:"43–44",title:"L'economia è dentro la società (Polanyi)",
  brief:"L'economia è l'insieme di istituzioni e azioni che servono a soddisfare i bisogni, e dipende da cultura, valori, istruzione, tecnologia, storia, politica, diritto e risorse naturali. Per Karl Polanyi l'attività economica è embedded nella società.",
  hook:"Conseguenza per le organizzazioni: non sono sistemi chiusi. È un'idea che tornerà con la teoria dei sistemi.",
  ex:"IBM in Svizzera, in India o negli USA segue leggi del lavoro, culture e aspettative diverse, anche con la stessa strategia globale.",
  q:"Perché non basta l'organigramma per capire un'azienda?",
  a:"Perché struttura, processi e decisioni sono influenzati da norme, istituzioni, politica e cultura dell'ambiente in cui l'azienda è immersa."},
 {id:"s12",part:"Cap. 2",slides:"45–48",title:"Tre modi di far circolare le cose",
  brief:"Reciprocità: dare e ricevere per relazione e obbligo reciproco (\"ti aiuto, un giorno qualcuno aiuterà me\"). Redistribuzione: un centro raccoglie e ridistribuisce (tasse, tempio, Stato). Scambio di mercato: soldi, prezzi, contratti (\"pago per ciò che voglio\").",
  hook:"Società ⊃ economia ⊃ organizzazioni: per capire un'organizzazione devi costruire un ponte verso il suo ambiente.",
  ex:"Dentro un'azienda: il salario è mercato, il budget centrale assegnato ai reparti è redistribuzione, il collega che ti aiuta senza che tu lo chieda è reciprocità.",
  q:"Un team riceve il budget annuale dalla sede centrale. Quale forma è?",
  a:"Redistribuzione: un centro raccoglie risorse e decide come allocarle."},
 {id:"s13",part:"Cap. 2",slides:"49–51",title:"Esercizio: dove avviene davvero lo scambio?",type:"sort",
  brief:"L'esercizio fatto in classe, ora interattivo. Scegli la forma per ogni esempio.",
  hook:"La lezione della slide: le categorie non sono sempre nette, e più logiche coesistono. Le economie reali raramente usano un solo meccanismo.",
  items:[["Comprare un caffè al bar","M"],["Pagare le tasse","R"],["Un amico ti aiuta a traslocare","C"],["Ricevere l'indennità di disoccupazione","R"],["I genitori si prendono cura dei figli","C"],["Comprare una bici usata online","M"],["Un'azienda paga il salario a un dipendente","M"],["I vicini condividono gli attrezzi","C"],["L'università pubblica","R"],["Dipendenti che aiutano i colleghi senza che nessuno lo chieda","C"]]},
 {id:"s14",part:"Cap. 3",slides:"53–54",title:"Un secolo di domande sulle organizzazioni",type:"timeline",
  brief:"Ogni epoca ha posto una domanda nuova, perché il mondo delle organizzazioni era cambiato. Le teorie non si cancellano a vicenda: si sommano.",
  hook:"Il trucco per ricordarle: ogni lente è la risposta al limite di quella precedente.",
  q:"Qual è il grande cambio di domanda tra la lente classica e la contingency?",
  a:"Da \"qual è il modo migliore di organizzarsi?\" a \"non esiste un modo migliore: dipende dal contesto\"."},
 {id:"s15",part:"Cap. 3",slides:"55–58",lens:"cls",title:"Classica: la fabbrica da far funzionare",
  brief:"Con l'industrializzazione le organizzazioni crescono e il lavoro va diviso, standardizzato e coordinato su larga scala. Design tipico: gerarchia chiara, divisione del lavoro, ruoli e regole formali, processi standard; il management pianifica e controlla, i dipendenti eseguono.",
  hook:"Divide → Specialize → Standardize → Control → Optimize. La struttura permette di crescere, ma troppo controllo rende rigidi.",
  ex:"Dal video su Toyota: lavoro standardizzato e misura dei tempi sono ancora logica classica. Ma gli operai possono fermare la linea e migliorare il processo: pensano, non solo eseguono.",
  q:"Cosa resta oggi della lente classica?",
  a:"Job description, organigrammi, SOP e processi standard, KPI, responsabilità gerarchica."},
 {id:"s16",part:"Cap. 3",slides:"59–62",lens:"hr",title:"Human Relations: ci sono persone dentro la macchina",
  brief:"La teoria classica trattava i dipendenti come parti del sistema produttivo. Mayo, Maslow, Herzberg e McGregor si chiedono cosa succede se si considera il lato umano e sociale.",
  hook:"Le persone sono motivate da più del denaro, i gruppi informali influenzano la performance, e le assunzioni del management plasmano il design dell'organizzazione.",
  ex:"Oggi: engagement, team development, leadership development, psychological safety, employee experience, cultura.",
  q:"Cosa aggiunge questa lente rispetto alla classica, in una frase?",
  a:"Le organizzazioni non sono solo strutture e processi, ma anche reti di persone e relazioni."},
 {id:"s17",part:"Cap. 3",slides:"63–65",lens:"dec",title:"Decisionale: nessuno sa tutto",
  brief:"Le teorie precedenti assumevano che i manager potessero trovare la soluzione migliore. Simon lo contesta: informazioni incomplete, alternative limitate, tempo e capacità cognitive limitate. Si sceglie una soluzione abbastanza buona (satisficing), e le organizzazioni creano regole e routine per aiutare le decisioni.",
  hook:"Il design organizzativo è anche design delle decisioni: chi riceve quali informazioni, e chi può decidere cosa?",
  ex:"Razionalità perfetta: tutte le informazioni e tutte le alternative → decisione ottimale. Razionalità limitata: informazioni incomplete → decisione soddisfacente.",
  q:"Cosa significa satisficing?",
  a:"Scegliere la prima opzione che supera una soglia accettabile, invece di cercare all'infinito quella ottimale."},
 {id:"s18",part:"Cap. 3",slides:"66–67",lens:"sys",title:"Sistemi: tutto è collegato",
  brief:"Uno dei cambi concettuali più grandi. Prima si guardava soprattutto dentro l'organizzazione; ora la domanda è come interagisce con il suo ambiente. Prospettiva sociotecnica: tecnologia, persone, struttura e processi vanno ottimizzati insieme.",
  hook:"Nuova tecnologia → cambiano i processi → cambiano i lavori → cambiano le competenze → cambia la collaborazione → cambia la struttura.",
  ex:"Introdurre l'AI generativa in un'azienda come IBM non è un progetto IT: è un cambiamento di ruoli, competenze e coordinamento.",
  q:"Cosa resta oggi della lente dei sistemi?",
  a:"Digital transformation, ecosistemi organizzativi, systems thinking, processi end-to-end, interdipendenze."},
 {id:"s19",part:"Cap. 3",slides:"68–69",lens:"con",title:"Contingency: dipende",
  brief:"La classica cercava il modo migliore di organizzarsi; la contingency risponde che non esiste. Il design adatto dipende da strategia, ambiente, tecnologia, dimensione, incertezza, persone e capacità.",
  hook:"Un buon design organizzativo non copia le best practice: crea fit.",
  ex:"Ambiente stabile: gerarchia, specializzazione e standard possono funzionare. Ambiente dinamico: decentramento, team e sperimentazione funzionano meglio.",
  q:"Cita due dibattiti di oggi che sono pura contingency.",
  a:"Agile vs gerarchico, centralizzato vs decentrato, strutture funzionali vs per prodotto, remoto vs ufficio, startup vs corporate."},
 {id:"s20",part:"Cap. 3",slides:"70–71",lens:"eco",title:"Economica: perché non tutto è mercato?",
  brief:"Transaction Cost Economics: a volte comprare sul mercato è efficiente, a volte conviene portare l'attività dentro l'organizzazione, a seconda dei costi di coordinamento. Agency Theory: attori diversi hanno interessi diversi (azionisti e management), quindi servono incentivi, monitoraggio, governance e contratti.",
  hook:"I confini dell'organizzazione e la governance esistono in parte per gestire transazioni, incentivi e interessi in conflitto.",
  ex:"Oggi: outsourcing, partnership strategiche, corporate governance, sistemi di incentivi, piattaforme, decisioni make-or-buy.",
  q:"Qual è la domanda di fondo di questa lente?",
  a:"Perché esistono le organizzazioni, invece di coordinare tutto tramite il mercato?"},
 {id:"s21",part:"Cap. 3",slides:"72–73",lens:"ins",title:"Istituzionale: essere legittimi",
  brief:"L'efficienza non spiega ogni decisione. A volte si adottano pratiche perché sono considerate legittime, professionali, attese, socialmente accettabili. Le pressioni sono tre: regolazione, norme professionali, imitazione (isomorfismo istituzionale).",
  hook:"Le organizzazioni non cercano solo efficienza, cercano anche legittimità.",
  ex:"Perché tutti adottano report di sostenibilità, politiche di diversity, metodi agili, strategie AI, uffici di compliance?",
  q:"Perché le organizzazioni dello stesso settore diventano sempre più simili?",
  a:"Per pressioni regolatorie (leggi), normative (professioni ed esperti) e mimetiche (copiare chi sembra avere successo)."},
 {id:"s22",part:"Cap. 3",slides:"76–81",title:"Theory Detective: Alpine Manufacturing",type:"detective",
  brief:"Azienda industriale svizzera con 800 dipendenti. Negli ultimi due anni:",
  facts:["la produttività è calata","il turnover è aumentato","le decisioni richiedono troppo tempo","i reparti lavorano sempre più a silos","i clienti vogliono personalizzazione più rapida","i concorrenti introducono nuove tecnologie digitali","il management ha risposto con più regole e reporting"],
  hook:"È il formato dell'esame, e del progetto. Scegli una lente: quale problema vede, cosa raccomanda, cosa si perde?",
  q:"Dopo aver provato tutte le lenti: perché la risposta del management (più regole) è probabilmente sbagliata?",
  a:"È una risposta puramente classica a un problema che diverse lenti leggono come mancanza di fit (contingency), motivazione (HR), colli di bottiglia decisionali (decisionale) e disallineamento tecnologico (sistemi). Più controllo rischia di peggiorare silos, lentezza e turnover."},
 {id:"s23",part:"Chiusura",slides:"82–83",title:"Un'organizzazione moderna è tutto questo insieme",
  brief:"L'eredità dell'era industriale (gerarchia, pianificazione centralizzata, divisione funzionale, standardizzazione, budget e controllo) ha funzionato per efficienza, prevedibilità e scalabilità. Fatica con incertezza, cambiamento rapido, innovazione e lavoro cross-funzionale.",
  hook:"Non esiste una sola diagnosi corretta: ogni teoria fa una domanda diversa.",
  ex:"Un'organizzazione moderna è contemporaneamente una macchina, un sistema sociale, un sistema decisionale, un sistema aperto, un sistema contingente, un sistema economico e un attore istituzionale.",
  q:"Collega ogni metafora alla sua lente e al bisogno che esprime.",
  a:"Macchina → classica: i processi devono essere efficienti. Sistema sociale → HR: le persone devono collaborare. Sistema decisionale → decisionale: le informazioni devono diventare decisioni. Sistema aperto → sistemi: dipende dall'ambiente. Sistema contingente → contingency: la struttura deve adattarsi al contesto. Sistema economico → economica: incentivi e transazioni contano. Attore istituzionale → istituzionale: legittimità e aspettative della società contano."},
 {id:"s24",part:"Chiusura",slides:"85–86",title:"Come saranno le prossime lezioni",
  brief:"Ogni lezione: benvenuto e recap; ogni gruppo presenta i progressi in 5 minuti (lavoro fatto, key learnings, aiuto necessario); feedback e apprendimento di gruppo; lezione con esercizi e riflessione; input facoltativi o studio autonomo.",
  hook:"To do per il 30.09: iniziare a studiare per l'esame, iniziare la desk research, conoscere l'azienda, raccogliere le prime osservazioni.",
  ex:"Per il Gruppo 2: arrivare con prime osservazioni su scopo, stakeholder, struttura e processi di IBM, già etichettate come FACT o ASSUMPTION.",
  q:"Cosa porta il tuo gruppo nei 5 minuti di aggiornamento?",
  a:"Lavoro fatto, key learnings, aiuto necessario."}
];
const ERAS=[["1900s","cls","Come organizzare il lavoro in modo efficiente?"],["1930s","hr","Che ruolo hanno persone, motivazione e relazioni?"],["1940s","dec","Come decidono davvero persone e organizzazioni?"],["1950s","sys","Come interagisce l'organizzazione con il suo ambiente?"],["1960s","con","Quale design si adatta a quale situazione?"],["1970s →","eco","Perché certe scelte organizzative? (economica)"],["1970s →","ins","Perché le organizzazioni diventano simili? (istituzionale)"]];
const UI={
 langName:"Italiano",lang:"Lingua",
 eyebrow:["OSP-1 · Joël Maier","HSLU DMI · Autunno 2026","Cap. 1–3"],
 h1a:"Sette lenti,",h1b:"un solo perché",
 lede:"Ogni teoria fa una domanda diversa alla stessa organizzazione. Qui non impari definizioni: impari [[cosa vede]] ogni lente, cosa le sfugge e come riconoscerla in uno scenario d'esame. Tocca un nome sottolineato per scoprire chi era e perché conta.",
 legend:"Il giallo sale quando rispondi bene alle domande di quella lente, in Detective o in Coppie. Tocca una lente per aprirne la scheda.",
 mastered:"padroneggiato",
 tabs:{lesson:"Lezione 1",podcast:"Podcast",cards:"Schede",quiz:"Detective",pairs:"Coppie"},
 found:"Fondamenta",lensT:"Lente teorica",idea:"Idea centrale",ideaHide:"Prova a spiegarla con parole tue, poi controlla.",
 why:"Perché è nata · perché conta",reason:"Come ragiona su un caso",sees:"Vede",rec:"Raccomanda",blind:"Non vede",
 seesHide:"Quale problema vedrebbe?",recHide:"Cosa proporrebbe?",blindHide:"Qual è il suo punto cieco?",
 signals:"Segnali in uno scenario d'esame",facts:"Fun facts",vx:"Palestra IBM · spunti da verificare con fonti",
 recall:"Ripasso attivo: nascondi le risposte",tapReveal:"tocca per rivelare",
 trainOn:"Allenati su",fAll:"Tutte le domande",fNew:"Non ancora indovinate",fWrong:"Da ripassare",fOnly:"Solo",
 session:"Sessione",toReview:"Da ripassare",deckDone:"Mazzo finito",nothing:"Niente da mostrare",
 deckDoneText:"Hai risposto bene a {ok} domande su {done}. Le sbagliate finiscono in \"Da ripassare\".",
 nothingText:"Con questo filtro non ci sono domande. Prova \"Tutte le domande\".",
 restart:"Ricomincia",caseN:"Caso",examLike:"EN · come all'esame",vxTag:"Palestra IBM",
 right:"Giusta · perché",notThis:"Non è questa · perché",connect:"Collega",nextCase:"Prossimo caso →",openCard:"Apri la scheda",
 sentence:"Frase",roundEnd:"Fine giro",whichLens:"Quale lente parla?",pRight:"Giusta",pNo:"No",pNext:"Avanti →",
 roundDone:"Giro completato",roundText:"{ok} su {done}. Le coppie che confondi di più sono quelle da portare all'esame.",reshuffle:"Mischia e rifai",
 example:"Esempio",simple:"In parole semplici",check:"Mini-check · rispondi prima nella tua testa",showAns:"Mostra una risposta possibile",
 card:"Scheda",done:"✓ Capito",markDone:"Segna come capito",back:"← Indietro",fwd:"Avanti →",step:"Tappa",slide:"Slide",
 detPick:"Scegli una lente e prova prima a rispondere a voce: poi confronta.",detProb:"Problema principale",detRec:"Raccomandazione",detBlind:"Punto cieco",
 sort:{M:"Mercato",R:"Redistribuzione",C:"Reciprocità"},
 pWorld:"Il suo mondo · perché se lo chiedeva",pSaid:"Cosa ha detto",pToday:"Dove lo ritrovi oggi",pWork:"Opera chiave",pConfuse:"Non confonderlo con",
 wiki:"Approfondisci su Wikipedia (EN) ↗",close:"Chiudi",
 profile:{eyebrow:"Prima di iniziare",title:"Crea il tuo profilo",intro:"Scrivi il tuo nome e scegli un PIN. Con lo stesso nome e PIN ritrovi risposte, tappe della lezione, podcast e appunti su qualsiasi dispositivo.",introLocal:"Scrivi il tuo nome e scegli un PIN. I progressi restano salvati in questo browser.",name:"Nome",pin:"PIN (4–8 cifre)",enter:"Entra",recent:"Profili usati su questo dispositivo",pinNote:"Il PIN serve solo a non confondere due persone con lo stesso nome: non usare un PIN che usi altrove.",errName:"Scrivi un nome di almeno 2 lettere.",errPin:"Il PIN deve avere da 4 a 8 cifre.",errWrong:"Questo nome esiste già con un altro PIN. Controlla il PIN, oppure aggiungi l'iniziale del cognome per creare un profilo nuovo.",errNet:"Non riesco a raggiungere il salvataggio online. Riprova tra poco.",loading:"Carico il profilo…",switchP:"Cambia profilo",remote:"Salvato online · {t}",local:"Salvato su questo dispositivo",saving:"Salvataggio…",err:"Salvataggio online non riuscito: riprovo al prossimo cambiamento.",devicePin:"Il PIN di questo profilo è cambiato: entra di nuovo."},
 pod:{
  title:"Podcast · Week 1",
  intro:"Il podcast della prima settimana (circa 21 minuti). Ascoltarlo in modo attivo vale molto più che ascoltarlo in sottofondo.",
  speed:"Velocità",back15:"−15 s",fwd15:"+15 s",resume:"Riprendi da dove eri rimasto",
  methodT:"Come ascoltarlo per ricordare",
  method:["Prima di premere play, leggi le tre domande qui sotto: il cervello ascolta meglio se sa cosa cercare.","Ogni 5 minuti circa, metti in pausa e annota un'idea con parole tue, più la lente del corso a cui si collega.","Quando senti un nome (Taylor, Polanyi, Simon…) cerca il suo profilo nelle Schede: cosa aggiunge il podcast?","Alla fine, senza riascoltare, rispondi alle domande. Dove ti blocchi, torna indietro di 15 secondi alla volta."],
  qT:"Tre domande da tenere in testa",
  qs:["Quale assunzione su persone, bisogni o scarsità emerge, e che conseguenze ha sull'organizzazione?","Quale teoria del Cap. 3 viene spiegata meglio nel podcast che nelle slide? Perché?","Cosa potresti usare subito per il progetto su IBM, separando FACT da ASSUMPTION?"],
  notesT:"I tuoi appunti",notesPh:"Minuto · idea con parole tue · lente collegata",notesHint:"Gli appunti restano salvati solo in questo browser.",
  mark:"Aggiungi il minuto attuale"
 }
};
OSP.it={UI,LENSES,QUIZ,PAIRS,PEOPLE,LESSON,ERAS};
})();
